### ISSUE TITLE
Live Redeploy option is not working

### ISSUE THREAD

**Issue by jrongs** [eclipse/vert.x#1252]
I am trying out vert.x 3.2.0, the live redeploy option appears to be broken:

john@vbox:~/wokspace/vertx/cae$ $ vertx run -cp target/classes --redeploy="**/*.class" io.mytest.HelloWorld
Starting the vert.x application in redeploy mode 
Starting vert.x application...
c7dc08f2-693e-4dfe-8312-62c17d0595a7-redeploy
java.lang.ClassNotFoundException: run
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)
Dec 21, 2015 11:03:45 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
SEVERE: Failed in deploying verticle
java.lang.ClassNotFoundException: run
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)

java.lang.ClassNotFoundException: run
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.JavaVerticleFactory.createVerticle(JavaVerticleFactory.java:42)
	at io.vertx.core.impl.DeploymentManager.createVerticles(DeploymentManager.java:186)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$153(DeploymentManager.java:159)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:132)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:104)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:92)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:546)
	at io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer.deploy(VertxIsolatedDeployer.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.core.impl.launcher.commands.ClasspathHandler.deploy(ClasspathHandler.java:160)
	at io.vertx.core.impl.launcher.commands.RunCommand.deploy(RunCommand.java:373)
	at io.vertx.core.impl.launcher.commands.RunCommand.run(RunCommand.java:247)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.execute(VertxCommandLauncher.java:230)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:365)
	at io.vertx.core.impl.launcher.VertxCommandLauncher.dispatch(VertxCommandLauncher.java:328)
	at io.vertx.core.Launcher.main(Launcher.java:48)

**Comment by cescoffier** [comment]
You need to append --launcher-class=io.vertx.core.Launcher to your command line (see http://vertx.io/blog/automatic-redeployment-in-eclipse-ide/)

**Comment by jrongs** [comment]
@cescoffier  thanks for the quick response and detailed write up on this particular feature.  tried on command line and eclipse IDE, worked great!
