### ISSUE TITLE
Provide  a way to force request state to become 'ended' after invoking response.end()

### ISSUE THREAD

**Issue by yfinkelstein** [eclipse/vert.x#1261]
I know this is a tricky subject, but the problem is real. Here is my scenario. I'm implementing an API method that allows the client to update a server resource with a new content PROVIDED the resource is already known on the server. A nice way of doing it is to have the client wait for 100-Continue before sending in the update stream itself which can be quite large.  Since the URL contains the resource ID the server can look it up first, and only if exists signal the client to proceed. However, if the resource does not exist, the server would reply with an error status and the client would not send the update. The connection can remain open and ready for the next request.

However, with vert.x this is apparently not possible...

Here is what I'm doing at a bit lower level:

1. In httpserverconfig I use handle100ContinueAutomatically = false
2. Upon receiving request, the server extracts the resource ID from the URL and checks for the resource availability status.
3. If resource available, do
```
               if (isExpect100Continue())
                    response.writeContinue();
```
then proceed with setting up request handler as usual.
4. If resource is not available, do
```
response.setStatusCode (404).end ("some error message);
```

What I see: 
In the case of resource being available, everything works as expected.
In the case of resource being not available, the connection becomes unusable and all subsequent client requests arriving on that connection simply time out. In that state, the following is what I see in my log (in my code I log these states after invoking "request.end()"):

```
request.isEnded()=false, rc.response.ended()=true, rc.response.bytesWritten()=65
```

This clearly shows that request is not 'ended' since really the client did not send any data expecting 100-continue but instead getting 404 (btw, I'm using standard apache http client and it behaves flawlessly in the scenario above)

This may lead to a bigger question: perhaps the right answer is to expose 'drainAndEnd ()' method on the request to ensure that nothing remains in the request pipeline and forcing the end state? Http/2 has this feature built-in.

**Comment by yfinkelstein** [comment]
An ugly but effective workaround is to this before invoking response.end(..):
```
      if (!routingContext.request().isEnded()) {
            log.warn ("signaling "Connection: Close" to the client since we are ending the request prematurely");
            response.putHeader(HttpHeaders.CONNECTION, "Close");
        }
```

**Comment by vietj** [comment]
what is your client ?

**Comment by yfinkelstein** [comment]
```
        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>2.6.3</version>
        </dependency>
```
```

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>fluent-hc</artifactId>
            <version>2.6.3</version>
        </dependency>

```
In the client, to wait for 100-Continue:

```
org.apache.http.client.fluent.Request req = ...
req.body (multipartEntityBuilder.build()).useExpectContinue();
```

**Comment by vietj** [comment]
I cannot find version 2.6.3 of httpcomponents.

according to what you are saying, it looks like you are using keep alive or pipelining. can you provide a simple example using this client that shows the behavior ? for instance an Post with Expect:100-continue request responsed with a 404 then  followed by one or several Get requests that are not processed by Vert.x HttpServer

**Comment by yfinkelstein** [comment]
I corrected the version error: it's 4.5.1.
I will send you a little client and server samples illustrating the problem end to end

**Comment by vietj** [comment]
any news about this ?

**Comment by yfinkelstein** [comment]
Ok, here is the client test:

```
package oneHundredContinue;

import org.apache.http.HttpResponse;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.fluent.Executor;
import org.apache.http.client.fluent.Request;
import org.apache.http.entity.ByteArrayEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;

import java.io.IOException;

/**
 * Demonstrates the issue with vert.x handling of 100-Continue when the server rejects the request.
 */
@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class Test {
    static final Executor executor;
    static {
        RequestConfig config = RequestConfig.custom()
                .setSocketTimeout(5000)
                .setConnectTimeout(5000)
                .setConnectionRequestTimeout(5000)
                .build();
        CloseableHttpClient client = HttpClientBuilder.create().setDefaultRequestConfig(config).build();
        executor = Executor.newInstance(client);
    }
    static final ByteArrayEntity payload = new ByteArrayEntity("some large chunk of data".getBytes());


    @org.junit.Test
    public void t01_serverSendsOk () throws IOException {
        doRequestResponse(true, 1);
    }

    @org.junit.Test
    public void t_02_serverSendsError () throws IOException {
        doRequestResponse(false, 2);
    }

    @org.junit.Test
    public void t_03_serverSendsOk () throws IOException {
        doRequestResponse(true, 3);
    }

    private void doRequestResponse (boolean serverShouldReplyWithOk, int seqno) throws IOException {
        Request request = Request
                .Put("http://localhost:8080/test100/" + String.valueOf(seqno))
                .addHeader("TEST_SENDOK", String.valueOf (serverShouldReplyWithOk))
                .body (payload).useExpectContinue();

        HttpResponse response = executor.execute (request).returnResponse();
        System.out.println (String.format ("response code: %d\tpayload=%s",
                response.getStatusLine().getStatusCode(), EntityUtils.toString (response.getEntity())));

    }
}

```
This produces the following output:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running oneHundredContinue.Test
response code: 200	payload=some large chunk of data
response code: 404	payload=cannot update non-existent resource
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.435 sec <<< FAILURE! - in oneHundredContinue.Test
t_03_serverSendsOk(oneHundredContinue.Test)  Time elapsed: 0.009 sec  <<< ERROR!
org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
	at oneHundredContinue.Test.doRequestResponse(Test.java:55)
	at oneHundredContinue.Test.t_03_serverSendsOk(Test.java:46)


Results :

Tests in error: 
  Test.t_03_serverSendsOk:46->doRequestResponse:55 » NoHttpResponse localhost:80...

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

Here is the server code:
```
        router.put    ("/test100/*").handler (rc ->{
            log.info ("/test100 is called with {}", rc.normalisedPath());
            boolean sendOk = Boolean.valueOf (rc.request().getHeader("TEST_SENDOK"));
            if (sendOk) {
                rc.response().writeContinue();
                rc.request().bodyHandler (buff-> rc.response().end (buff));
            } else {
                rc.request().bodyHandler (buff-> log.info ("ignoring input {}", buff.toString()));
                rc.response().setStatusCode(404).end ("cannot update non-existent resource");
            }
            rc.response().bodyEndHandler (ignore->log.info ("isEnded={}", rc.request().isEnded()));
        });
```

On the console of the server I see the following after running the tests:
```
2016-01-08 13:34:32,239 INFO  [vert.x-eventloop-thread-1] o.m.service.RoutesV1 - /test100 is called with /test100/1
2016-01-08 13:34:32,251 INFO  [vert.x-eventloop-thread-1] o.m.service.RoutesV1 - isEnded=true
2016-01-08 13:34:32,259 INFO  [vert.x-eventloop-thread-1] o.m.service.RoutesV1 - /test100 is called with /test100/2
2016-01-08 13:34:32,262 INFO  [vert.x-eventloop-thread-1] o.m.service.RoutesV1 - ignoring input PUT /test100/3 HTTP/1.1
2016-01-08 13:34:32,264 ERROR [vert.x-eventloop-thread-1] i.v.c.n.i.ConnectionBase - java.lang.IllegalArgumentException: text is empty

```

Note that the server prints isEnded=true only once, and then logs some strange error. I did not have time to find the place where that exception is logged and why. In my real application, I don't see this exception, and the client simply times out waiting for response for the Next request on the same connection after the server replies 404 to 100-Continue

**Comment by yfinkelstein** [comment]
For the client test, I use

```
        <httpcomponents.version>4.5.1</httpcomponents.version>
        <httpcomponents.httpcore.version>4.4.4</httpcomponents.httpcore.version>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpcore</artifactId>
            <version>${httpcomponents.httpcore.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpclient</artifactId>
            <version>${httpcomponents.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>httpmime</artifactId>
            <version>${httpcomponents.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.httpcomponents</groupId>
            <artifactId>fluent-hc</artifactId>
            <version>${httpcomponents.version}</version>
        </dependency>
```

**Comment by yfinkelstein** [comment]
To make it easier to understand what's going on here is the output on the client with wire-level debug enabled:

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running oneHundredContinue.Test
13:56:32.469 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
13:56:32.481 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:8080][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
13:56:32.492 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://localhost:8080][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
13:56:32.494 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Opening connection {}->http://localhost:8080
13:56:32.501 [main] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connecting to localhost/127.0.0.1:8080
13:56:32.507 [main] DEBUG o.a.h.i.c.DefaultHttpClientConnectionOperator - Connection established 127.0.0.1:58134<->127.0.0.1:8080
13:56:32.508 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
13:56:32.509 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request PUT /test100/1 HTTP/1.1
13:56:32.509 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
13:56:32.511 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
13:56:32.514 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> PUT /test100/1 HTTP/1.1
13:56:32.515 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> TEST_SENDOK: true
13:56:32.515 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 24
13:56:32.516 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:8080
13:56:32.517 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
13:56:32.517 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)
13:56:32.518 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
13:56:32.519 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
13:56:32.519 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /test100/1 HTTP/1.1[\r][\n]"
13:56:32.520 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "TEST_SENDOK: true[\r][\n]"
13:56:32.520 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 24[\r][\n]"
13:56:32.521 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:8080[\r][\n]"
13:56:32.521 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
13:56:32.522 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)[\r][\n]"
13:56:32.522 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
13:56:32.523 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:56:32.523 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
13:56:32.575 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 100 Continue[\r][\n]"
13:56:32.576 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
13:56:32.578 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 100 Continue
13:56:32.579 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "some large chunk of data"
13:56:32.581 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
13:56:32.581 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 24[\r][\n]"
13:56:32.582 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
13:56:32.582 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "some large chunk of data"
13:56:32.583 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
13:56:32.583 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 24
13:56:32.586 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
13:56:32.588 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://localhost:8080] can be kept alive indefinitely
13:56:32.589 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:8080][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
response code: 200	payload=some large chunk of data
13:56:32.591 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
13:56:32.592 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:8080][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
13:56:32.592 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://localhost:8080][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
13:56:32.592 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
13:56:32.593 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request PUT /test100/2 HTTP/1.1
13:56:32.593 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
13:56:32.594 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
13:56:32.594 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> PUT /test100/2 HTTP/1.1
13:56:32.594 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> TEST_SENDOK: false
13:56:32.594 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 24
13:56:32.595 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:8080
13:56:32.595 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
13:56:32.595 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)
13:56:32.595 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
13:56:32.596 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
13:56:32.596 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /test100/2 HTTP/1.1[\r][\n]"
13:56:32.597 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "TEST_SENDOK: false[\r][\n]"
13:56:32.597 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 24[\r][\n]"
13:56:32.597 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:8080[\r][\n]"
13:56:32.598 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
13:56:32.598 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)[\r][\n]"
13:56:32.599 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
13:56:32.599 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:56:32.600 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
13:56:32.602 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 404 Not Found[\r][\n]"
13:56:32.602 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 35[\r][\n]"
13:56:32.603 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
13:56:32.603 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "cannot update non-existent resource"
13:56:32.603 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 404 Not Found
13:56:32.604 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 35
13:56:32.604 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection can be kept alive indefinitely
13:56:32.604 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection [id: 0][route: {}->http://localhost:8080] can be kept alive indefinitely
13:56:32.605 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:8080][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
response code: 404	payload=cannot update non-existent resource
13:56:32.606 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
13:56:32.606 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection request: [route: {}->http://localhost:8080][total kept alive: 1; route allocated: 1 of 2; total allocated: 1 of 20]
13:56:32.607 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection leased: [id: 0][route: {}->http://localhost:8080][total kept alive: 0; route allocated: 1 of 2; total allocated: 1 of 20]
13:56:32.607 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: set socket timeout to 5000
13:56:32.607 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Executing request PUT /test100/3 HTTP/1.1
13:56:32.607 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Target auth state: UNCHALLENGED
13:56:32.608 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Proxy auth state: UNCHALLENGED
13:56:32.608 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> PUT /test100/3 HTTP/1.1
13:56:32.608 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> TEST_SENDOK: true
13:56:32.608 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 24
13:56:32.609 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: localhost:8080
13:56:32.609 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
13:56:32.609 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)
13:56:32.609 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
13:56:32.610 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Accept-Encoding: gzip,deflate
13:56:32.610 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /test100/3 HTTP/1.1[\r][\n]"
13:56:32.610 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "TEST_SENDOK: true[\r][\n]"
13:56:32.611 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 24[\r][\n]"
13:56:32.611 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: localhost:8080[\r][\n]"
13:56:32.611 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
13:56:32.612 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: Apache-HttpClient/4.5.1 (Java/1.8.0_66)[\r][\n]"
13:56:32.612 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
13:56:32.613 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Accept-Encoding: gzip,deflate[\r][\n]"
13:56:32.613 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
13:56:32.614 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "end of stream"
13:56:32.614 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "some large chunk of data"
13:56:32.615 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "end of stream"
13:56:32.615 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Close connection
13:56:32.616 [main] DEBUG o.a.h.i.c.DefaultManagedHttpClientConnection - http-outgoing-0: Shutdown connection
13:56:32.616 [main] DEBUG o.a.h.impl.execchain.MainClientExec - Connection discarded
13:56:32.617 [main] DEBUG o.a.h.i.c.PoolingHttpClientConnectionManager - Connection released: [id: 0][route: {}->http://localhost:8080][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.501 sec <<< FAILURE! - in oneHundredContinue.Test
t_03_serverSendsOk(oneHundredContinue.Test)  Time elapsed: 0.016 sec  <<< ERROR!
org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
	at oneHundredContinue.Test.doRequestResponse(Test.java:55)
	at oneHundredContinue.Test.t_03_serverSendsOk(Test.java:46)


Results :

Tests in error: 
  Test.t_03_serverSendsOk:46->doRequestResponse:55 » NoHttpResponse localhost:80...

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by vietj** [comment]
Hi,

in this case I believe that this is due to the behavior of Apache Http Client with a final status code (i.e a a non 100 Continue response). I dig a bit the HTTP spec and it says that a server should either close the connection or ignore the request entity:

_A server that responds with a final status code before reading the entire message body SHOULD indicate in that response whether it intends to close the connection or continue reading and discarding the request message_

The client should send the request entity because the server has not closed the connection.

What you call an _ugly workaround_ is actually the right thing to do according to this. Probably the server documentation should be updated with to explain to do this in this situation.

**Comment by vietj** [comment]
Lot of useful explanations here : http://curl.haxx.se/mail/lib-2004-08/0002.html

**Comment by yfinkelstein** [comment]
I guess you are right "by the book", but this basically kills the idea behind Expect/Continue as a mechanism to avoid sending payload when the server says "do not". I would consider deviating from the spec and offering a flag to to reset the connection state after server replies with code != 100. The thread says it "may" cause "some" client to get confused, but 2 major clients - cURL and apache http/java, - will be  perfectly happy.

**Comment by purplefox** [comment]
If you want the connection to be closed when a resource is not available why don't you just close it yourself from the server (response.close()) ?

**Comment by yfinkelstein** [comment]
Why would I want a (keep alive) connection to be closed after a normal request response interaction? That's the whole point - there is no need to close it. But I'm forced to.

**Comment by purplefox** [comment]
I don't really understand why it doesn't work the way you expect. It would be a lot simpler to diagnose if you provided a reproducer which uses the Vert.x http client at the client side.

**Comment by purplefox** [comment]
We have tests in the test suite that test the 100-continue functionality. If you can adapt one of those so it fails it would be a good place to start.

**Comment by yfinkelstein** [comment]
I did provide both the client and server code to reproduce it, pls see above. The reason it does not work is that vert.x request continues to stay in in the state "not ended" even though the response.end() was invoked by me. So, any subsequent IO on that activity goes towards the previous request which is already abandoned.

**Comment by purplefox** [comment]
Ok, but response.end() ends the *response* not the request. The request won't be ended until it has been fully read from the wire - you don't have any control over that.

Like I say, if you could adapt one of the existing 100 continue tests that would be a great place to start :)

**Comment by yfinkelstein** [comment]
if you and Viet  disagree that any code changes is required why do you suggest to add more tests? I can do it, and it will show that in that particular scenario the test fails. So what if this is "by the book"?

I'm also not sure why do you say  
>The request won't be ended until it has been fully read from the wire - you don't have any control over that.

Surely we can have a method on the request to perform "hard reset" of the connection state so that for next reset the parser starts from the beginning.

**Comment by vietj** [comment]
as I said before, if you don't close the connection (either using close() or with Connection: close header) the client should send the request body and the server accept it. It looks like the apache client does not send the request body and I think it does not behave correctly.

**Comment by yfinkelstein** [comment]
It just does not make sense, it defeats the idea of expect/continue. If the client says "should I continue?" and server says "no" - why should the client continue sending the remaining part of the request? It's a flaw in http spec, a glitch in the wording the caused somebody to misinterpret it and now it's too late to change. 

I give up :) Closing the connection is not the end of the world.

**Comment by purplefox** [comment]
Yes, this is why I asked for a test using the Vert.x http client :)

If the client is not sending the request body then the server will wait for ever for the body that it's expecting to arrive, so the request on the server will always be in the ended state? What else can the server do here.

If there really is an issue in the Vert.x implementation then it should be possible to replicate the issue by adapting one of the existing 100 continue tests. If you can do that I will investigate it further.

**Comment by purplefox** [comment]
I don't think it's a flaw in the spec. If the server says "no" then the client *does not* have to send the entire (possibly large) request body that it would have sent if the server had responded "yes", but it *does* need to complete and end the request - the request could have an empty body.

All http requests that are written onto a pipelined connection need to strictly conform to the HTTP protocol (i.e. end with \r\n\r\n) - this signifies that the request has ended and can be followed by the next one. If the request is not ended by the client then the server has no idea when one request ends and the next one begins.

**Comment by yfinkelstein** [comment]
Hmm, that's an interesting point. That point has not been mentioned anywhere above or in the thread that Viet has quoted: http://curl.haxx.se/mail/lib-2004-08/0002.html. It would make sense to me as it disambiguates the uncertainty about what's coming next on that connection. 

So, to confirm this with 100% clarity, which of the statements below is correct in your opinion?

After sending "Expect: Continue"  header and receiving status != OK
1.  Every http client should send \r\n\r\n and recycle the connection (assuming it's a keep alive connection and the server did not send "Connection:Close") 
(Btw, should the client also send "Content-Length: 0"?)
2. If vert.x http server sees this behavior it will mark the request 'ended' and recycle the connection gracefully
3. vert.x http client behaves this way too

When I say "recycle the connection" I mean perform whatever is normally done upon graceful completion of a request/response interaction. For the client this means returning it to the pool of open connections such that the next request can choose it. For the server this means resetting the parser state so that it's able to parse the next request.

**Comment by vietj** [comment]
you could just send \r\n\r\n but if you set a content-length that would produce an request. You should used chunked transfer encoding to make this correct.

**Comment by yfinkelstein** [comment]
ok, I will try this. 

(Btw, sorry I thought Viet was your first name, I apologize).

**Comment by purplefox** [comment]
You shouldn't need to do anything special. Any correct client/server should work this way already.
