### ISSUE TITLE
Websocket deadlock during handshake

### ISSUE THREAD

**Issue by vietj** [eclipse/vert.x#1343]
Affects 3.2.1

```
"test-akka.actor.default-dispatcher-1854" - Thread t@1934
   java.lang.Thread.State: WAITING
    at java.lang.Object.wait(Native Method)
    - waiting on <101efae> (a io.netty.util.concurrent.PromiseTask)
    at java.lang.Object.wait(Object.java:502)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
    at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
    at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
    at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:546)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:333)
    at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:304)
    at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:176)
    at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:145)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$null$26(HttpServerImpl.java:570)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler$$Lambda$47/6681436.run(Unknown
Source)
    at io.vertx.core.http.impl.ServerWebSocketImpl.connect(ServerWebSocketImpl.java:257)
    at io.vertx.core.http.impl.ServerWebSocketImpl.writeFrame(ServerWebSocketImpl.java:229)
    - locked <150f83c> (a io.vertx.core.http.impl.ServerConnection)
    at io.vertx.core.http.impl.ServerWebSocketImpl.writeFinalTextFrame(ServerWebSocketImpl.java:239)
    at com.tomas.test.actor.ConnectionHandlerActor.com$tomas$test$actor$ConnectionHandlerActor$$sendToClient(ConnectionHandlerActor.scala:118)
    at com.tomas.test.actor.ConnectionHandlerActor.sendToClient(ConnectionHandlerActor.scala:127)
    at com.tomas.test.actor.ConnectionHandlerActor.handleUnknownUser(ConnectionHandlerActor.scala:131)
    at com.tomas.test.actor.ConnectionHandlerActor.preStart(ConnectionHandlerActor.scala:70)
    at akka.actor.Actor$class.aroundPreStart(Actor.scala:470)
    at com.tomas.test.actor.ConnectionHandlerActor.aroundPreStart(ConnectionHandlerActor.scala:40)
    at akka.actor.ActorCell.create(ActorCell.scala:580)
    at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456)
    at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478)
    at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:279)
    at akka.dispatch.Mailbox.run(Mailbox.scala:220)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:231)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

   Locked ownable synchronizers:
    - None


"vert.x-eventloop-thread-1" - Thread t@13
   java.lang.Thread.State: BLOCKED
    at io.vertx.core.http.impl.ServerWebSocketImpl.isRejected(ServerWebSocketImpl.java:272)
    - waiting to lock <150f83c> (a
io.vertx.core.http.impl.ServerConnection) owned by
"test-akka.actor.default-dispatcher-1854" t@1934
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$handshake$27(HttpServerImpl.java:583)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler$$Lambda$46/6399973.run(Unknown
Source)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$16(ContextImpl.java:333)
    at io.vertx.core.impl.ContextImpl$$Lambda$22/11074884.run(Unknown Source)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.handshake(HttpServerImpl.java:554)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:509)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:420)
    at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:85)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1070)
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:912)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:369)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
    at java.lang.Thread.run(Thread.java:744)
```

**Comment by vietj** [comment]
Explanation:

Here is what happens Vert.x http server process an server websocket handshake and receives an websocket upgrade header:
-  the websocket handshake calls the HttpServer#websocketHandler `wsConn.handleWebsocketConnect(ws)`
- after the handler has been called is the websocket has not been rejected by the handler then the handshake is terminated by the webserver calling `ws.connectNow()` and the Netty handshake is terminated (101 response + channel pipeline is updated)
- when the websocketHandler is called it can trigger an implicit handshake termination, for instance writing a frame to the client, that calls the same connect

here is what happens in this case

1/ the websocketHandler passes the websocket reference to an akka thread
2/ the akka thread writes a frame that cause the handshake to terminate while holding the server connection lock
3/ during the handshake Netty modifies the channel pipeline
4/ the channel pipeline modification (handler removal) makes a blocking wait for a modification done on the server connection event loop : waitForFuture is called in DefaultChannelPipeline
5/ as it is asynchronous the handshake event loop thread continues and calls `isRejected` on the server connection to decide if it should reject the websocket , the `isRejected` attempts to get the lock of the server connection

The deadlock happens because the akka thread holds the server connection lock and waits for the pipeline modification to happen (i.e it waits for the execution of a task in the event loop) . The current event loop task waits for the server connection lock.

Workaround: wait until the websocket handshake, delaying with a Context.runOnContext in the websocketHandler should probably work.

**Comment by vietj** [comment]
A reproducer might be possible with:

1. in the websocket handler write a frame in a separate thread and wait a little (perhaps wait until the thread writing the frame is in state WAITING)
2. exit the handler and let the http server finish the handshake

**Comment by vietj** [comment]
cf also WebsocketTest#testWriteFromConnectHandler that gives a concrete example of how it happens from the event loop.

**Comment by vietj** [comment]
Actually a better workaround is to not write to the websocket itself but instead write a frame via the EventBus using the WebSocket#binaryHandlerID() . This will pass the frame from the Akka thread to the event loop and write the frame without causing this potential deadlock:

```
Buffer b = getSomeBuffer()
String address = websocket.binaryHandlerID()
EventBus eventBus = vertx.eventBus();
eventBus.send(address, b);
```

**Comment by vietj** [comment]
Possible solution (there might be several solutions) : in `writeFrame` call `connect`outside of the synchronized block (but set connected=true in the synchronized block). The connect  runnable does non _seem_ to need to run under synchronization as it modifies the _connectionMap_ (ConcurrentMap) and calls the Netty pipeline modification.

**Comment by vietj** [comment]
note for 3.3 : rather fix after the http2 branch has been merged to avoid conflicts and unnecessary waste of time

**Comment by purplefox** [comment]
Looks like something is trying to write frames from the wrong thread (i.e. not following the Vert.x threading model)

**Comment by vietj** [comment]
this does not happen anymore with Netty 4.1.1.Final and Vert.x 3.3 as the DefaultChannelPipeline modification is now possible from another thread : https://github.com/netty/netty/commit/8fe3c83e4ca9a64c03f5adcb9f056d9e9440a389#diff-6b8633f415085302023f47004357891a

**Comment by tmihalcin** [comment]
ran into similar problem when using vertx only implementation (no akka)

"vert.x-eventloop-thread-4" #16 prio=5 os_prio=0 tid=0x02394800 nid=0x501f in Object.wait() [0x6159e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:255)
	- locked <0x6b5a3140> (a io.netty.util.concurrent.PromiseTask)
	at io.netty.util.concurrent.DefaultPromise.await(DefaultPromise.java:33)
	at io.netty.util.concurrent.AbstractFuture.get(AbstractFuture.java:32)
	at io.netty.channel.DefaultChannelPipeline.waitForFuture(DefaultChannelPipeline.java:667)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:558)
	at io.netty.channel.DefaultChannelPipeline.replace(DefaultChannelPipeline.java:509)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:192)
	at io.netty.handler.codec.http.websocketx.WebSocketServerHandshaker.handshake(WebSocketServerHandshaker.java:145)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$null$28(HttpServerImpl.java:571)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler$$Lambda$25/20934282.run(Unknown Source)
	at io.vertx.core.http.impl.ServerWebSocketImpl.connect(ServerWebSocketImpl.java:257)
	at io.vertx.core.http.impl.ServerWebSocketImpl.writeFrame(ServerWebSocketImpl.java:229)
	- locked <0x6b5a3388> (a io.vertx.core.http.impl.ServerConnection)
	at io.vertx.core.http.impl.ServerWebSocketImpl.writeFinalTextFrame(ServerWebSocketImpl.java:239)
	at com.mihalcin.chef.web.WebSocketHandlerVerticle.sendToClient(WebSocketHandlerVerticle.java:180)
	at com.mihalcin.chef.web.WebSocketHandlerVerticle.handleUnknownUser(WebSocketHandlerVerticle.java:122)
	at com.mihalcin.chef.web.WebSocketHandlerVerticle.start(WebSocketHandlerVerticle.java:95)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$163(DeploymentManager.java:429)
	at io.vertx.core.impl.DeploymentManager$$Lambda$4/30018916.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.vertx.core.impl.ContextImpl$$Lambda$5/14437415.run(Unknown Source)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- None


"vert.x-eventloop-thread-2" #14 prio=5 os_prio=0 tid=0x02193000 nid=0x4efd waiting for monitor entry [0x634fd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at io.vertx.core.http.impl.ServerWebSocketImpl.connectNow(ServerWebSocketImpl.java:264)
	- waiting to lock <0x6b5a3388> (a io.vertx.core.http.impl.ServerConnection)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.lambda$handshake$29(HttpServerImpl.java:590)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler$$Lambda$24/311979.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$5/14437415.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.handshake(HttpServerImpl.java:555)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:510)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:421)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:85)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:277)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:264)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1052)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:895)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:292)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:278)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:962)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:744)

   Locked ownable synchronizers:
	- None

**Comment by vietj** [comment]
can you give a spin with 3.3.0.CR2 ?

**Comment by tmihalcin** [comment]
i'll try it out

**Comment by tmihalcin** [comment]
so far so good
If I won't report problems in the next 1-2 months, it's probably ok :)
