### ISSUE TITLE
Vertx.clusteredVertx() handler not called if cannot bind to address

### ISSUE THREAD

**Issue by danadam** [eclipse/vert.x#1375]
When starting clustered vetx instance:

``` java
Vertx.clusteredVertx(
        new VertxOptions()
            .setClustered(true)
            .setClusterHost("127.0.0.1")
            .setClusterPort(9999),
        result ->
        {
            System.out.println("Cluster started");
        }
    );
```

if it cannot bind to the address it prints the exception:

```
io.vertx.core.impl.VertxImpl SEVERE: Failed to start event bus
java.net.BindException: Address already in use
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:125)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:485)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1089)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:440)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:425)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:903)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:198)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:348)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

and the result handler is never called.

The problem seems to be in `io.vertx.core.impl.VertxImpl.createAndStartEventBus()` where only error is logged and the `resultHandler` is not called:

``` java
} else {
  log.error("Failed to start event bus", ar2.cause());
}
```

**Comment by vietj** [comment]
would you mind to contribute a test for this and possibly a fix ?
