### ISSUE TITLE
Problem with getting netSocket() in the middle.

### ISSUE THREAD

**Issue by testn** [eclipse/vert.x#1395]
I got this exception from time to time when trying to call HttpClientResponse#netSocket() while the data is streaming using Vert.x 3.2.1. I cannot create a consistent reproduction yet.

```
 io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalStateException: Invalid object UnpooledUnsafeHeapByteBuf(ridx: 0, widx: 8192, cap: 8192)
	at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:911)
	at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:847)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$20(VertxHttpHandler.java:80)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:216)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.remove0(CombinedChannelDuplexHandler.java:595)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.remove(CombinedChannelDuplexHandler.java:580)
	at io.netty.channel.CombinedChannelDuplexHandler.handlerRemoved(CombinedChannelDuplexHandler.java:173)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:517)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved(DefaultChannelPipeline.java:511)
	at io.netty.channel.DefaultChannelPipeline.remove0(DefaultChannelPipeline.java:343)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:315)
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
	at io.vertx.core.http.impl.ClientConnection.createNetSocket(ClientConnection.java:396)
	at io.vertx.core.http.impl.HttpClientResponseImpl.netSocket(HttpClientResponseImpl.java:263)
	                            .
                                    .
                                    .
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:220)
	at io.vertx.core.http.impl.ClientConnection.handleResponseChunk(ClientConnection.java:283)
	at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:876)
	at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:847)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$20(VertxHttpHandler.java:80)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:307)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:293)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:840)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by vietj** [comment]
can you run vertx testsuite and tell if you observe similar exceptions ?

**Comment by testn** [comment]
How do I do that?

**Comment by vietj** [comment]
what is your use case for using netsocket in the middle ?

**Comment by testn** [comment]
Remember that we discussed this earlier? I was using it to force close the socket.

**Comment by vietj** [comment]
ok and now you can use the new connection().close() to I think we can close this one.

**Comment by testn** [comment]
sure.
