### ISSUE TITLE
ClassNotFound when io.netty.handler.proxy is not included for the proxy functions

### ISSUE THREAD

**Issue by alexlehm** [eclipse/vert.x#1452]
The proxy code tries to catch a NoClassDefFoundError when the optional proxy handler jar is not included in the pom, but it still gives a NoClassDefFoundError.

To check the issue, I have created a small verticle project with fatjar that uses the proxy, which gives the following exception:

````
java.lang.NoClassDefFoundError: io/netty/handler/proxy/ProxyHandler
        at io.vertx.core.http.impl.ConnectionManager$ChannelConnector.connect(ConnectionManager.java:420)
        at io.vertx.core.http.impl.ConnectionManager$ConnQueue.createNewConnection(ConnectionManager.java:286)
        at io.vertx.core.http.impl.ConnectionManager$ConnQueue.getConnection(ConnectionManager.java:229)
        at io.vertx.core.http.impl.ConnectionManager.getConnectionForRequest(ConnectionManager.java:146)
        at io.vertx.core.http.impl.HttpClientImpl.getConnectionForRequest(HttpClientImpl.java:681)
        at io.vertx.core.http.impl.HttpClientRequestImpl.connect(HttpClientRequestImpl.java:614)
        at io.vertx.core.http.impl.HttpClientRequestImpl.write(HttpClientRequestImpl.java:738)
        at io.vertx.core.http.impl.HttpClientRequestImpl.end(HttpClientRequestImpl.java:334)
        at cx.lehmann.vertx.ProxyRequestVerticle.start(ProxyRequestVerticle.java:32)
        at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
````

**Comment by alexlehm** [comment]
created the issue in issues project instread
