### ISSUE TITLE
java.lang.ClassCastException when removing a keyset of Shareable entities of a ConcurrentSharedMap

### ISSUE THREAD

**Issue by ebrigand** [eclipse/vert.x#1474]
Version used: 
- Vert.x 2.1.6
- Java 8

I'm trying to clear the cache using vert.x shared data and I get an exception.

Knowing that: 

> keySet returns a Set view of the keys contained in this map. The set is backed by the map, so changes to the map are reflected in the set, and vice-versa.

Code to clear the cache:

```
    private void clearCache() {
        ConcurrentSharedMap<KeyCache, String> lookupCache = vertx.sharedData().getMap("lookups");
        lookupCache.keySet().removeIf(keyCache -> keyCache.getDataType().equals(schema.getString("dataType")));
    }
```

My KeyCache class implements Shareable and override equals and hashcode for 2 private String.

Exception:

```
java.lang.ClassCastException: com.tesco.disco.shareable.KeyCache cannot be cast to com.tesco.disco.shareable.KeyCache
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1540)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at com.tesco.disco.indexer.workers.Indexer.clearCache(Indexer.java:66)
        at com.tesco.disco.indexer.workers.Indexer.handle(Indexer.java:131)
        at com.tesco.disco.indexer.workers.Indexer.handle(Indexer.java:30)
        at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
        at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
        at java.lang.Thread.run(Thread.java:745)

```

And I think there is another issue, because if I am using a String as a key of the SharedMap, and if I want to clear it, I have to do it one by one using the Map:remove(Object key), if I use Collection:removeIf(Predicate<? super E> filter), it does not work, see example below:

Example:

```
private void clearCache() {
        ConcurrentSharedMap<String, String> lookupCache = vertx.sharedData().getMap("lookups");
        //Copy the elements of the sharedMap into a new hashMap
        Map<String, String> copy = lookupCache.entrySet().stream().collect(Collectors.toMap(e -> e.getKey(), e -> e.getValue()));
        //SharedMap: removeIf does not work, lookupCache still filled
        lookupCache.keySet().removeIf(key -> key.startsWith(schema.getString("dataType") + Transformer.DATA_TYPE_CACHE_SEPARATOR));
        //HashMap: removeIf works, copy is empty
        copy.keySet().removeIf(key -> key.startsWith(schema.getString("dataType") + Transformer.DATA_TYPE_CACHE_SEPARATOR));
        //SharedMap: Solution to remove the cache entries
        for (String keyCache : lookupCache.keySet()) {
            if(keyCache.startsWith(schema.getString("dataType") + Transformer.DATA_TYPE_CACHE_SEPARATOR)){
                lookupCache.remove(keyCache);
            }
        }
    }
```

**Comment by tsegismont** [comment]
Closing: Vert.x 2 is no longer maintained
