### ISSUE TITLE
NoClassDefFoundError netty: ChannelMatchers & ByteBufUtil$HexUtil

### ISSUE THREAD

**Issue by theborakompanioni** [eclipse/vert.x#1500]
I get a NoClassDefFoundError when stopping a small application:
```
2016-07-06 15:49:19,770 [vert.x-eventloop-thread-1] WARN  io.vertx.core.impl.ContextImpl - Failed to run close hooks
java.lang.NoClassDefFoundError: io/netty/channel/group/ChannelMatchers
	at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:226)
	at io.vertx.core.http.impl.HttpServerImpl.actualClose(HttpServerImpl.java:506)
	at io.vertx.core.http.impl.HttpServerImpl.close(HttpServerImpl.java:420)
	at io.vertx.core.impl.ContextImpl.runCloseHooks(ContextImpl.java:148)
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.lambda$null$2(DeploymentManager.java:532)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:111)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:116)
	at my.example.RestServerVerticle.stop(RestServerVerticle.java:51)
	at io.vertx.core.impl.DeploymentManager$DeploymentImpl.lambda$doUndeploy$3(DeploymentManager.java:547)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:359)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:339)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:393)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.channel.group.ChannelMatchers
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 common frames omitted
2016-07-06 15:49:20,977 [vert.x-acceptor-thread-0] WARN  i.n.c.AbstractChannelHandlerContext - An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.lang.NoClassDefFoundError: io/netty/buffer/ByteBufUtil$HexUtil
	at io.netty.buffer.ByteBufUtil.hexDump(ByteBufUtil.java:123)
	at io.netty.channel.DefaultChannelId.asShortText(DefaultChannelId.java:240)
	at io.netty.channel.AbstractChannel.toString(AbstractChannel.java:385)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.forceClose(ServerBootstrap.java:260)
	at io.netty.bootstrap.ServerBootstrap$ServerBootstrapAcceptor.channelRead(ServerBootstrap.java:254)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:326)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1320)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:334)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:905)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:504)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:385)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: io.netty.buffer.ByteBufUtil$HexUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 common frames omitted
2016-07-06 15:51:19,725 [Thread-3] ERROR i.v.c.i.l.commands.RunCommand - Timed out waiting to undeploy all
```

my.example.RestServerVerticle is a simple verticle spinning up an http-server:
```
    @Override
    public void start(Future<Void> startFuture) {
        log.info("Starting {}...", name);

        int port = port();
        Router router = router();

        vertx.createHttpServer(new HttpServerOptions())
                .requestHandler(router::accept)
                .listenObservable(port)
                .toSingle()
                .subscribe(server -> {
                    log.info("Started {} on port {}", name, server.actualPort());
                    startFuture.complete();
                }, startFuture::fail);
    }

    @Override
    public void stop(Future<Void> stopFuture) {
        log.info("stopped {}", name);
        stopFuture.complete();
    }
```
I am using the `maven-shade-plugin` to build  a fat jar.
Any guidance on this is highly appreciated.

**Comment by vietj** [comment]
can you provide a reproducer ?

**Comment by theborakompanioni** [comment]
@vietj Wow. You are quite responsive :-)
Just saw that the class files are present in my local build, but do not get packaged on my build server.
So I cannot pinpoint the erroneous step at the moment. I'll come back to you with more information.

**Comment by theborakompanioni** [comment]
@vietj Sorry for the late reply - could not yet provide a reproducer in a reliable way. Should I post here again or open a new issue once I have something to show?
