### ISSUE TITLE
Play 2.5.4 + vertx 3.3.0 error on startup

### ISSUE THREAD

**Issue by efiko12** [eclipse/vert.x#1505]
Hello Vert.x,

I'm getting an error when I'm running play service with vertx 3.3.0
If  I remove vertx dependency, Play service running fine.
I didn't have this problem with vertx 3.2.1 
 
Thanks,
Effi

Here is the exception stack trace

--- (Running the application, auto-reloading is enabled) ---

io.netty.channel.ChannelException: Unable to create Channel from class class io.netty.channel.socket.nio.NioServerSocketChannel
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:41)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:318)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:246)
	at play.core.server.NettyServer.bind(NettyServer.scala:139)
	at play.core.server.NettyServer.play$core$server$NettyServer$$bindChannel(NettyServer.scala:224)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:216)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:225)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
Caused by: java.lang.NoSuchMethodError: io.netty.channel.DefaultChannelId.newInstance()Lio/netty/channel/DefaultChannelId;
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:105)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:77)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:87)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:84)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:70)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at io.netty.channel.ReflectiveChannelFactory.newChannel(ReflectiveChannelFactory.java:39)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:318)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:282)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:246)
	at play.core.server.NettyServer.bind(NettyServer.scala:139)
	at play.core.server.NettyServer.play$core$server$NettyServer$$bindChannel(NettyServer.scala:224)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at play.core.server.NettyServer$$anonfun$1.apply(NettyServer.scala:216)
	at scala.Option.map(Option.scala:146)
	at play.core.server.NettyServer.<init>(NettyServer.scala:216)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:279)
	at play.core.server.NettyServerProvider.createServer(NettyServer.scala:278)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:225)
	at play.core.server.DevServerStart$$anonfun$mainDev$1.apply(DevServerStart.scala:61)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.core.server.DevServerStart$.mainDev(DevServerStart.scala:60)
	at play.core.server.DevServerStart$.mainDevHttpMode(DevServerStart.scala:50)
	at play.core.server.DevServerStart.mainDevHttpMode(DevServerStart.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at play.runsupport.Reloader$.startDevMode(Reloader.scala:234)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.devModeServer$lzycompute$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.play$sbt$run$PlayRun$$anonfun$$anonfun$$anonfun$$devModeServer$1(PlayRun.scala:74)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:100)
	at play.sbt.run.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:53)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
[trace] Stack trace suppressed: run 'last compile:run' for the full output.
[error] (compile:run) java.lang.reflect.InvocationTargetException
[error] Total time: 1 s, completed 12:30:48 09/07/2016
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0

Process finished with exit code 1

**Comment by vietj** [comment]
Hi,

I think it’s because Vert.x 3.3 uses Netty 4.1.x and Play 2.5.4 still uses Netty 4.0.x

Julien

**Comment by efiko12** [comment]
Thanks vietj

**Comment by vietj** [comment]
see https://groups.google.com/forum/#!msg/play-framework/UUDZZRpAv3w/QKRZeW07BAAJ
