### ISSUE TITLE
Unexpected FileSystemException

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#1527]
Today my iOS mobile browser Safari 9 produced a lot of mystifying requests to the same URL which produces the following stacktrace: 

`2016-07-20 20:59:39,496 INFO [vert.x-eventloop-thread-2] [n.v.WebserverAndSockJsServer] - --------- Node request: http://mathias-lenovo/loginpage  
2016-07-20 20:59:39,502 INFO [vert.x-eventloop-thread-2] [n.v.WebserverAndSockJsServer] - --------- Node request: http://mathias-lenovo/loginpage  
2016-07-20 20:59:39,510 INFO [vert.x-eventloop-thread-2] [n.v.WebserverAndSockJsServer] - --------- Node request: http://mathias-lenovo/loginpage  
2016-07-20 20:59:39,512 ERROR [vert.x-eventloop-thread-2] [i.v.e.w.i.RoutingContextImplBase] - Unexpected exception in route io.vertx.core.VertxException: java.nio.file.FileSystemException: .vertx\file-cache-872f340f-a24a-4479-9037-925e7ef96eb7\login.html: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:153)
	at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:119)
	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:657)
	at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:437)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:334)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:52)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:275)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:262)
	at node.verticles.WebserverAndSockJsServer.lambda$1(WebserverAndSockJsServer.java:266)
	at node.verticles.WebserverAndSockJsServer$$Lambda$85/502338848.handle(Unknown Source)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at node.verticles.WebserverAndSockJsServer$1.handle(WebserverAndSockJsServer.java:207)
	at node.verticles.WebserverAndSockJsServer$1.handle(WebserverAndSockJsServer.java:1)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at io.vertx.ext.web.handler.impl.FaviconHandlerImpl.handle(FaviconHandlerImpl.java:161)
	at io.vertx.ext.web.handler.impl.FaviconHandlerImpl.handle(FaviconHandlerImpl.java:33)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
	at node.verticles.WebserverAndSockJsServer$$Lambda$108/1751816372.handle(Unknown Source)
	at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:274)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:392)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:134)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:471)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:420)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$5(VertxHttpHandler.java:80)
	at io.vertx.core.http.impl.VertxHttpHandler$$Lambda$129/1172179503.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$13/1656168062.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: .vertx\file-cache-872f340f-a24a-4479-9037-925e7ef96eb7\login.html: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:165)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:149)
	... 50 common frames omitted
 
2016-07-20 20:59:39,513 INFO [vert.x-eventloop-thread-2] [n.v.WebserverAndSockJsServer] - --------- Node request: http://mathias-lenovo/loginpage  
2016-07-20 20:59:39,516 INFO [vert.x-eventloop-thread-2] [n.v.WebserverAndSockJsServer] - --------- Node request: http://mathias-lenovo/loginpage  
2016-07-20 20:59:39,518 ERROR [vert.x-eventloop-thread-2] [i.v.e.w.i.RoutingContextImplBase] - Unexpected exception in route io.vertx.core.VertxException: java.nio.file.FileSystemException: .vertx\file-cache-872f340f-a24a-4479-9037-925e7ef96eb7\login.html: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:153)
	at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:119)
	at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:657)
	at io.vertx.core.http.impl.HttpServerResponseImpl.doSendFile(HttpServerResponseImpl.java:437)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:334)
	at io.vertx.core.http.impl.HttpServerResponseImpl.sendFile(HttpServerResponseImpl.java:52)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:275)
	at io.vertx.core.http.HttpServerResponse.sendFile(HttpServerResponse.java:262)
	at node.verticles.WebserverAndSockJsServer.lambda$1(WebserverAndSockJsServer.java:266)
	at node.verticles.WebserverAndSockJsServer$$Lambda$85/502338848.handle(Unknown Source)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at node.verticles.WebserverAndSockJsServer$1.handle(WebserverAndSockJsServer.java:207)
	at node.verticles.WebserverAndSockJsServer$1.handle(WebserverAndSockJsServer.java:1)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at io.vertx.ext.web.handler.impl.FaviconHandlerImpl.handle(FaviconHandlerImpl.java:161)
	at io.vertx.ext.web.handler.impl.FaviconHandlerImpl.handle(FaviconHandlerImpl.java:33)
	at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:221)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:93)
	at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
	at node.verticles.WebserverAndSockJsServer$$Lambda$108/1751816372.handle(Unknown Source)
	at io.vertx.core.http.impl.ServerConnection.handleRequest(ServerConnection.java:274)
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:392)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:134)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:471)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:420)
	at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$5(VertxHttpHandler.java:80)
	at io.vertx.core.http.impl.VertxHttpHandler$$Lambda$129/1172179503.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:333)
	at io.vertx.core.impl.ContextImpl$$Lambda$13/1656168062.run(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
	at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.FileSystemException: .vertx\file-cache-872f340f-a24a-4479-9037-925e7ef96eb7\login.html: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileCopy.copy(WindowsFileCopy.java:165)
	at sun.nio.fs.WindowsFileSystemProvider.copy(WindowsFileSystemProvider.java:278)
	at java.nio.file.Files.copy(Files.java:1274)
	at io.vertx.core.impl.FileResolver.unpackFromFileURL(FileResolver.java:149)
	... 50 common frames omitted`

The exception occurs while executing the following line of code in WebserverAndSockJsServer.java:266
**routingContext.response().sendFile("login.html");** and it leads to an parsing error on Safari.

Any ideas why a lot of requests are producing this exception?

**Comment by leolux** [comment]
Btw, I have disabled the file cache using the following line:
`System.getProperties().setProperty("vertx.disableFileCaching", "true");`

**Comment by vietj** [comment]
@leolux this seems to be a vertx web issue - can you close this one and open it there ?

**Comment by leolux** [comment]
Ok , thanks! I opened the issue there: https://github.com/vert-x3/vertx-web/issues/425
Btw, nice to see that github has introduced templates for issues.
