### ISSUE TITLE
Deadlock with HTTP proxy app

### ISSUE THREAD

**Issue by xkr47** [eclipse/vert.x#1535]
Hi,

I've [implemented a reverse HTTP proxy with vert.x-ceylon](https://github.com/xkr47/vhostproxy4) version 3.2.0. I have now several times found the app in deadlock state, after which it does not respond to new conncetion attempts anymore. Here is an example:

```java
Found one Java-level deadlock:
=============================
"vert.x-eventloop-thread-0":
  waiting to lock monitor 0x00007f81f4171048 (object 0x0000000771caaea8, a io.vertx.core.http.impl.ClientConnection),
  which is held by "vert.x-eventloop-thread-1"
"vert.x-eventloop-thread-1":
  waiting to lock monitor 0x00007f81f416bbb8 (object 0x00000007718aadb0, a io.vertx.core.http.impl.ServerConnection),
  which is held by "vert.x-eventloop-thread-0"

Java stack information for the threads listed above:
===================================================
"vert.x-eventloop-thread-0":
        at io.vertx.core.http.impl.HttpClientResponseImpl.resume(HttpClientResponseImpl.java:171)
        - waiting to lock <0x0000000771caaea8> (a io.vertx.core.http.impl.ClientConnection)
        at io.vertx.ceylon.core.http.HttpClientResponse.resume(HttpClientResponse.java:66)
        at io.vertx.ceylon.core.http.HttpClientResponse.resume(HttpClientResponse.java:21)
        at org.otherone.vhostproxy.vertx.MyPump$1.$call$(run.ceylon)
        at org.otherone.vhostproxy.vertx.MyPump$1.$call$(run.ceylon)
        at io.vertx.ceylon.core.http.HttpServerResponse$4.handle(HttpServerResponse.java:101)
        at io.vertx.ceylon.core.http.HttpServerResponse$4.handle(HttpServerResponse.java:99)
        at io.vertx.core.http.impl.HttpServerResponseImpl.handleDrained(HttpServerResponseImpl.java:538)
        - locked <0x00000007718aadb0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.http.impl.ServerConnection.handleInterestedOpsChanged(ServerConnection.java:296)
        - locked <0x00000007718aadb0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.http.impl.HttpServerResponseImpl.lambda$drainHandler$46(HttpServerResponseImpl.java:245)
        at io.vertx.core.http.impl.HttpServerResponseImpl$$Lambda$26/1183493945.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl$$Lambda$13/1679198612.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
"vert.x-eventloop-thread-1":
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:583)
        - waiting to lock <0x00000007718aadb0> (a io.vertx.core.http.impl.ServerConnection)
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:271)
        at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:52)
        at io.vertx.ceylon.core.http.HttpServerResponse.write(HttpServerResponse.java:84)
        at io.vertx.ceylon.core.http.HttpServerResponse.write(HttpServerResponse.java:20)
        at org.otherone.vhostproxy.vertx.MyPump.dataHandler$priv$(run.ceylon:60)
        at org.otherone.vhostproxy.vertx.MyPump.access$000(run.ceylon:58)
        at org.otherone.vhostproxy.vertx.MyPump$2.$call$(run.ceylon:91)
        at io.vertx.ceylon.core.http.HttpClientResponse$4.handle(HttpClientResponse.java:87)
        at io.vertx.ceylon.core.http.HttpClientResponse$4.handle(HttpClientResponse.java:85)
        at io.vertx.core.http.impl.HttpClientResponseImpl.handleChunk(HttpClientResponseImpl.java:220)
        - locked <0x0000000771caaea8> (a io.vertx.core.http.impl.ClientConnection)
        at io.vertx.core.http.impl.ClientConnection.handleResponseChunk(ClientConnection.java:283)
        at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:876)
        at io.vertx.core.http.impl.HttpClientImpl$ClientHandler.doMessageReceived(HttpClientImpl.java:847)
        at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$7(VertxHttpHandler.java:80)
        at io.vertx.core.http.impl.VertxHttpHandler$$Lambda$18/1592881354.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$3(ContextImpl.java:333)
        at io.vertx.core.impl.ContextImpl$$Lambda$13/1679198612.run(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:225)
        at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:80)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:124)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:354)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

The `org.otherone.vhostproxy.vertx.MyPump` class in the middle of both traces is a customized version of the standard `PumpImpl` class which adds just some logging after the write() call. It does not hold any locks when calling vert.x apis.

I strongly assume both threads are processing tasks related to the same request, since they lock against the same connection object, and in HTTP/1 only one response can be streaming data at once.

To me it seems the deadlock arises because in both HttpServerResponseImpl and HttpClientResponseImpl the methods involved in the deadlock all hold locks while calling both upstream and downstream methods. By downstream I mean the pump calling `HttpServerResponseImpl.write()` and `HttpClientResponseImpl.resume()`, and by upstream I mean `HttpServerResponseImpl.handleDrained()` and `HttpClientResponseImpl.handleChunk()` calling the pump.  The pump is located at the "top", coordinating traffic between two downstream connections. As can be seen all four vertx http methods hold or attempt to hold locks. Having written numerous proxy, router and gateway software products in the past I have learned that this locking model is not deadlock-safe. One robust solution to this is to decide on a locking model where locks are allowed to be held a) only while calling downstream code or b) only while calling upstream code. Locking-while-calling-downstream has seemed sensible to me so that's what I have used.

So if one would decide not to allow locks during upstream calls, the solution (where there is state that actually needs protection) is to introduce state instead. So for example `HttpClientResponseImpl.handleChunk()` that wants to deliver new stream data upstream, instead of doing (pseudocode):

```java
  private void handleChunk(byte[] data) {
    synchronized (lock) {
      dataHandler.handleData(data);
    }
  }

  private void doSomethingElse() {
    synchronized (lock) {
      // here we can assume a handleData call is not in progress and
      // don't need to worry about that situation
      ...
    }
  }
```

.. one could instead do:

```java
  enum State { IDLE, DATA };

  private State state = State.IDLE;

  private void handleChunk(byte[] data) {
    DataHandler dataHandlerSnapshot;
    synchronized(lock) {
      state = State.DATA;
      dataHandlerSnapshot = dataHandler;
    }
    dataHandlerSnapshot.handleData(data);
    synchronized (lock) {
      state = State.IDLE;
    }
  }

  private void doSomethingElse() {
    synchronized (lock) {
      // here we might need to take into account that a handleData
      // call is in progress and decide what to do if so
      ...
    }
  }
```

Introducing state variables typically makes the classes more complex as they may need to check whether they are "in the middle of something", but this should avoid deadlocks as long as it is clear what is upstream and what downstream. And in case it is not, don't hold locks when calling other components at all and use state in all cases..

To further visualize what I'm trying to say here, here's before & after sequence diagrams - arrows towards the pump are upstream calls and arrows away from te pump are downstream calls:

![](http://xkr47.outerspace.dyndns.org/tmp/vertx-before.png)

![](http://xkr47.outerspace.dyndns.org/tmp/vertx-after.png)

I would be interested in hearing what you think. I am considering looking deeper into the HTTP classes and see if I can get some pull requests going myself..

BR,
  xkr47

**Comment by vietj** [comment]
hi normally the http client and http server should use the same thread, that is the reason of your deadlock, it is not a vertx bug.

in your code replace:

```
shared void run() {
  // Content
}
```

by

```
shared void run() {
  value ctx = vertx.getOrCreateContext();
  ctx.runOnContext() {
    // Content
  }
}
```

Beside your should rather have this code in a Verticle, it would use the same Context automatically and you could scale it easily by deploying several instances.

**Comment by xkr47** [comment]
Astonishing and sorry for not getting the hang of verticles or contexts. Thank you!

**Comment by vietj** [comment]
I recommend reading also https://github.com/vietj/vertx-materials/blob/master/src/main/asciidoc/output/Demystifying_the_event_loop.adoc
