### ISSUE TITLE
Blocked thread warning when opening or closing an AsyncFile 

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#1573]
Users have reported blocked thread warning when opening or closing an AsyncFile.

Here are example stack traces:

```
io.vertx.core.VertxException: Thread blocked
        at java.io.UnixFileSystem.getBooleanAttributes0(Native Method)
        at java.io.UnixFileSystem.getBooleanAttributes(UnixFileSystem.java:242)
        at java.io.File.exists(File.java:819)
        at io.vertx.core.impl.FileResolver.resolveFile(FileResolver.java:103)
        at io.vertx.core.impl.VertxImpl.resolveFile(VertxImpl.java:657)
        at io.vertx.core.file.impl.FileSystemImpl$14.<init>(FileSystemImpl.java:736)
        at io.vertx.core.file.impl.FileSystemImpl.openInternal(FileSystemImpl.java:735)
        at io.vertx.core.file.impl.FileSystemImpl.open(FileSystemImpl.java:299)
        at io.vertx.core.http.impl.HttpServerFileUploadImpl.streamToFileSystem(HttpServerFileUploadImpl.java:148)
```

and

```
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.close0(Native Method)
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.close(WindowsAsynchronousFileChannelImpl.java:142)
	at io.vertx.core.file.impl.AsyncFileImpl.doClose(AsyncFileImpl.java:464)
	at io.vertx.core.file.impl.AsyncFileImpl.closeInternal(AsyncFileImpl.java:480)
	at io.vertx.core.file.impl.AsyncFileImpl.close(AsyncFileImpl.java:117)
	at io.vertx.rxjava.core.file.AsyncFile.close(AsyncFile.java:143)
```

One user provided more details and reported he was using a mapped Windows shared drive.

I have been able to reproduce the opening issue by a slow network filesystem (with twickle and nbd).

**Comment by luengnat** [comment]
@vietj / @tsegismont  doClose() should use the ```context``` field variable rather than doing ```context = Vertx.getOrCreateContext()```. Otherwise, if ```close()``` is called from the wrong thread, it will cause the callback to be called from the wrong thread as well.

**Comment by tsegismont** [comment]
I believe it is legal to call close from another thread. This PR didn't
change the behavior of close BTW (will execute the handler on the calling
thread if it's a vert.x thread, otherwise will pick an event loop)

2016-08-26 17:27 GMT+02:00 luengnat <notifications@github.com>:

**Comment by vietj** [comment]
good point @luengnat , in general common case it will be the right thread though (i.e if used from a verticle)

**Comment by vietj** [comment]
i.e `check()` would fail

**Comment by vietj** [comment]
@luengnat actually re-reading it, the code giving the callback should be made on the context of the close call. So it could be technically another context, i.e AsyncFile can be called from different threads although it is a good practice concerning performances

**Comment by luengnat** [comment]
AsyncFile can be called from any context but the context that it should call .executeBlocking should be the context that is used to create the file in the first place. This is to guarantee that the closeHandler callback is done from the right context. If you look at flush(), that is how it is implemented.

**Comment by vietj** [comment]
@luengnat I believe `doFlush` is wrong

That being said in the case of a Verticle, the cached `context` and the `vertx.getOrCreateContext()` will be the same. The `Verticle` is the advocated usage for Vert.x, so we are debating here the case of a developer that would create an `AsyncFile` in a particular context and then would `flush`/`close` it in another one.

**Comment by luengnat** [comment]
@vietj In most of the case they do but if it is ever called in the wrong context, I would expect it to do the right thing. Otherwise, it should throw a hard horrible error in such case to prevent people from doing so rather than working most of the time.

**Comment by vietj** [comment]
@luengnat agreed, if the callback is made from another context, it should be made on the context callback of the caller of `close` / `flush`
