### ISSUE TITLE
Asynchronous read/write done on wrong thread

### ISSUE THREAD

**Issue by shravanAngadi** [eclipse/vert.x#1598]
The open/close issue has been addressed [here #1573 ](https://github.com/eclipse/vert.x/pull/1574). Async read/write still is blocking.

2016-08-30 18:16:25,382 aaa  WARN (vertx-blocked-thread-checker) [io.vertx.core.impl.BlockedThreadChecker] - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 9988 ms, time limit is 2000
io.vertx.core.VertxException: Thread blocked
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.writeFile(Native Method)
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.access$500(WindowsAsynchronousFileChannelImpl.java:41)
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl$WriteTask.run(WindowsAsynchronousFileChannelImpl.java:635)
	at sun.nio.ch.WindowsAsynchronousFileChannelImpl.implWrite(WindowsAsynchronousFileChannelImpl.java:734)
	at sun.nio.ch.AsynchronousFileChannelImpl.write(AsynchronousFileChannelImpl.java:251)
	at io.vertx.core.file.impl.AsyncFileImpl.writeInternal(AsyncFileImpl.java:379)
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:374)
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:171)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:179)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:57)

at io.vertx.core.file.impl.AsyncFileImpl.writeInternal(AsyncFileImpl.java:378)
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:373)
	at io.vertx.core.file.impl.AsyncFileImpl.doWrite(AsyncFileImpl.java:170)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:178)
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:56)

**Comment by shravanAngadi** [comment]
The code works fine most of the time. A reproducers would be just a simple file read/write program which performs the operations on a very slow drive, say like a slow network drive.

**Comment by vietj** [comment]
can you give full stack trace ?

**Comment by shravanAngadi** [comment]
The stack I've provided includes the core vert.x classes then remainder of the stack is my custom code.

**Comment by shravanAngadi** [comment]
I've made the fix and tested it. Not able to check-in the changes as I don't have permissions on the repository. @vietj can you provide me permission so I can check-in the changes and raise a PR?

**Comment by vietj** [comment]
we need to full stack at least

**Comment by vietj** [comment]
on my machine the file channel is `SimpleAsynchronousFileChannelImpl` that is async via an executor, so it seems specific issue that does not always happen.

**Comment by vietj** [comment]
it seems that the issue on windows is related to the fact you are using a shared filesystem and that windows FS is supposed to be async, cf:

```
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/7u40-b43/sun/nio/ch/Iocp.java#453
```

**Comment by vietj** [comment]
so it seems more like a JDK defect

**Comment by tsegismont** [comment]
I think you're hitting this issue because you're working with a network share drive. Use a local drive or, as a workaround, rewrite this portion of your code with executeBlocking and the java.io blocking APIs.

It's interesting to note that Windows does not guarantee that async will be async...
https://support.microsoft.com/en-us/kb/156932

```
Be careful when coding for asynchronous I/O because the system reserves the right to make an operation synchronous if it needs to.
```
