### ISSUE TITLE
MessageConsumer close hook reports an IllegalStateException on the Context exception handler

### ISSUE THREAD

**Issue by cstub** [eclipse/vert.x#1625]
Since version 3.3.3 undeploying a Verticle which registered an event-bus handler throws the following exception:

```
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
	at io.vertx.core.eventbus.impl.EventBusImpl$$Lambda$24/431454548.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.vertx.core.impl.ContextImpl$$Lambda$13/1360657223.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

The problem seems to occur on applying the close-hook on an `EventBusImpl.HandlerEntry`.
Here `HandlerEntry.close()` is invoked with a completionHandler, which is handled successfully twice.

The first time it is handled directly in `HandlerEntry.close()`.

The second time it is handled through the chain:
```
HandlerEntry.close()
HandlerRegistration.unregister()
HandlerRegistration.doUnregister()
EventBus.removeRegistration()
EventBus.callCompletionHandlerAsync()
```

Up until version 3.3.3 this wasn’t a problem, as the `HandlerEntry.close()` was supplied with an anonymous completionHandler, but since version 3.3.3 it is supplied with a FutureImpl which throws an exception if handled multiple times with a success state.

The following code sample will reproduce the problem:

```
import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.eventbus.MessageConsumer;
import io.vertx.ext.unit.Async;
import io.vertx.ext.unit.TestContext;
import io.vertx.ext.unit.junit.VertxUnitRunner;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(VertxUnitRunner.class)
public class FailingUnregisterSpec {

  @Test
  public void test(final TestContext context) {
    final Vertx vertx = Vertx.vertx();
    final Async async = context.async();

    vertx.deployVerticle(TestVerticle.class.getName(), ar -> {
      vertx.undeploy(ar.result(), context.asyncAssertSuccess());
      async.complete();
    });
  }

  public static class TestVerticle extends AbstractVerticle {
    private MessageConsumer<Object> consumer;

    @Override
    public void start() throws Exception {
      consumer = vertx.eventBus().consumer("test", msg -> {
      });
    }

    @Override
    public void stop() throws Exception {
      // manual unregister gets rid of the problem
      // consumer.unregister();
    }
  }
}
```

**Comment by vietj** [comment]
is it a regression ?

**Comment by vietj** [comment]
can you confirm that this has no impact on the app, rather it's polluting the logs

**Comment by carlobertuccini** [comment]
I'd like to point out that it's not related only to verticle undeploy, but to any future usage

```
    Future<Object> future = Future.future();
    future.complete(null);
    future.result();
```

Will cause the logs errors.
It is surely a regression since it didn't happen on 3.3.2.

**Comment by cstub** [comment]
I haven't been able to fully check the impact on an application yet, but it breaks unit-tests if one follows the guidelines of Vert.x 3.3. 

```
@RunWith(VertxUnitRunner.class)
public class FailingUnregisterSpec {

  private Vertx vertx;

  @Before
  public void before(TestContext context) {
    vertx = Vertx.vertx();
    vertx.exceptionHandler(context.exceptionHandler());
  }

  @After
  public void after(TestContext context) {
    vertx.close(context.asyncAssertSuccess());
  }

  @Test
  public void test(final TestContext context) {
    final Async async = context.async();

    vertx.deployVerticle(TestVerticle.class.getName(), ar -> {
      vertx.undeploy(ar.result(), context.asyncAssertSuccess());
      async.complete();
    });
  }

  public static class TestVerticle extends AbstractVerticle {
    private MessageConsumer<Object> consumer;

    @Override
    public void start() throws Exception {
      consumer = vertx.eventBus().consumer("test", msg -> {
      });
    }

    @Override
    public void stop() throws Exception {
      // manual unregister gets rid of the problem
      // consumer.unregister();
    }
  }
}
```

**Comment by cstub** [comment]
The problem does not occur with Vert.x 3.3.2.

**Comment by vietj** [comment]
@carlobertuccini 

```
Future<Object> future = Future.future();
future.complete(null);
future.result();
```

works for me with 3.3.3

**Comment by vietj** [comment]
so here is what happen:

this commit changed the implementation of close hooks to use a `Future` (simplification):

https://github.com/eclipse/vert.x/commit/17d8c63018c3bf9e8f9ffb72662e894e308f6d72#diff-43c731a2afc8edffb803ee7ce14cfb5bR70

at the same time, the `completionHandler` is called twice (but that is before 3.3.3) :

https://github.com/eclipse/vert.x/blob/master/src/main/java/io/vertx/core/eventbus/impl/EventBusImpl.java#L541

the completionHandler is completed and passed to the unregister that will also complete it. We didn't notice before as the handler implementation was more tolerant than the `Future` implementation.

so it seems that the appropriate fix is to remove the `completionHandler.handle(Future.succeededFuture());` line in EventBusImpl

**Comment by vietj** [comment]
actually it's not a simplification, the future is introduced but I don't remember why

**Comment by vietj** [comment]
the point of the future seems to fail the future if it was not completed when the block throws an exception.

Overall I think that `complete()` and `fail()` method should not throw an IllegalStateException and instead return a boolean indicating wether the future was completed/failed or not. Or we should have method `tryComplete` and `tryFail` that do that. I don't think anyone is relying on the fact that the completion is quite aggressive.

**Comment by vietj** [comment]
@cstub so it fails because of 

```
vertx.exceptionHandler(context.exceptionHandler());
```

right ?

**Comment by vietj** [comment]
i'm trying to understand damage and evaluate the severity :-)

**Comment by cstub** [comment]
@vietj Thanks!

**Comment by vietj** [comment]
@cstub I think that you should use the work-around you mentionned (unregister manually the consumer) in the meantime and we will fix it in master for now.

**Comment by cstub** [comment]
@vietj I think I will rather stay at 3.3.2 for now, as I would have to change many components in our applications which are using the automatic clean-up right now.
Thx for taking care.

**Comment by vietj** [comment]
@cstub it does not affect automatic clean-up, it still happen. It just reports the IllegalStateException of the second completion to the Vertx#exceptionHandler which makes your test fail. S

**Comment by cstub** [comment]
@vietj Thanks for the clarification, I will have to adapt my tests then and remove the exceptionHandler of Vert.x 3.3.

```
@Before
public void before(TestContext context) {
  vertx = Vertx.vertx();
  // removing the handler fixes the issue for now
  // vertx.exceptionHandler(context.exceptionHandler());
}
```

**Comment by vietj** [comment]
@cstub you could check this specific exception by looking at Throwable#getStackTrace() in a filter

**Comment by cstub** [comment]
@vietj Thanks for the hint!

**Comment by goerge** [comment]
Any plans to release this as 3.3.4? It's really annoying.

**Comment by dano** [comment]
I guess it's probably too close to 3.4.0 for this, but a 3.3.4 with this fix would be appreciated. It pollutes logs, and seems to confuse lots of people, given the many duplicate issues opened, and threads on the mailing list referencing it.

**Comment by vietj** [comment]
after 3.4.0 beta we might do a 3.3.4 containing such fixes

**Comment by doctorpangloss** [comment]
This is a maddening exception that seems to be at the root of using any kind of testing with Vert.x; hopefully you can give some clear guidance as to what we can do right now, without changing any code, to address it?

**Comment by vietj** [comment]
you can find it fixed in 3.4.1

**Comment by hyginous29** [comment]
This error is coming with 3.4.2 version.(vertx-web-3.4.2)

 
[10/11/17 10:53:12:151 MST] 00000394 ContextImpl   E   Unhandled exception
                                 java.lang.IllegalStateException: Result is already complete: succeeded
at io.vertx.core.impl.FutureImpl.fail(FutureImpl.java:103)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl.lambda$doUndeploy$3(DeploymentManager.java:549)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl$$Lambda$106.0000000038003380.handle(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
at io.vertx.core.impl.ContextImpl$$Lambda$66.00000000A66087A0.run(Unknown Source)
at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
at io.vertx.core.impl.TaskQueue$$Lambda$63.00000000A53F8B10.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:785)
 
[10/11/17 10:52:45:842 MST] 00000170 DeploymentMan E   Failed to run close hook
                                 java.lang.NullPointerException
at org.eclipse.osgi.internal.loader.BundleLoader.findDynamicSource(BundleLoader.java:1068)
at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:474)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:422)
at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:410)
at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:836)
at java.lang.ClassLoader.loadClass(ClassLoader.java:823)
at com.ibm.ws.bootstrap.ExtClassLoader.loadClass(ExtClassLoader.java:134)
at java.lang.ClassLoader.loadClass(ClassLoader.java:803)
at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:62)
at com.ibm.ws.classloader.ProtectionClassLoader.loadClass(ProtectionClassLoader.java:58)
at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:617)
at java.lang.ClassLoader.loadClass(ClassLoader.java:803)
at com.ibm.ws.classloader.CompoundClassLoader.loadClass(CompoundClassLoader.java:617)
at java.lang.ClassLoader.loadClass(ClassLoader.java:803)
at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:428)
at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:163)
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:93)
at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:28)
at io.vertx.core.net.impl.NetSocketImpl.close(NetSocketImpl.java:243)
at io.vertx.core.net.impl.NetClientBase.close(NetClientBase.java:102)
at io.vertx.core.net.impl.NetClientBase.lambda$new$0(NetClientBase.java:68)
at io.vertx.core.net.impl.NetClientBase$$Lambda$26.000000001002BBF0.close(Unknown Source)
at io.vertx.core.impl.CloseHooks.run(CloseHooks.java:90)
at io.vertx.core.impl.ContextImpl.runCloseHooks(ContextImpl.java:129)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl.lambda$null$2(DeploymentManager.java:532)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl$$Lambda$110.0000000020006830.handle(Unknown Source)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:126)
at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:133)
at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:95)
at io.vertx.core.AbstractVerticle.stop(AbstractVerticle.java:126)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl.lambda$doUndeploy$3(DeploymentManager.java:547)
at io.vertx.core.impl.DeploymentManager$DeploymentImpl$$Lambda$107.00000000C80033C0.handle(Unknown Source)
at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
at io.vertx.core.impl.ContextImpl$$Lambda$12.0000000079350620.run(Unknown Source)
at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
at io.vertx.core.impl.TaskQueue$$Lambda$9.00000000796A7F10.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.lang.Thread.run(Thread.java:785)

**Comment by vietj** [comment]
the root cause seems to happen in OSGi, @cescoffier any idea ?
