### ISSUE TITLE
vertx.close() throws IlegalStateException: Result is already complete (since version 3.3.3)

### ISSUE THREAD

**Issue by tetv** [eclipse/vert.x#1628]
Unhandled exception 
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vietj** [comment]
duplicate https://github.com/eclipse/vert.x/issues/1625
