### ISSUE TITLE
Apparent dual completion of future during event bus close hooks

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#1640]
Vertx version -- 3.3.3

Upon switching to 3.3.3 we are seeing a very high volume of the following exceptions in our test logs:

```
Sep 23, 2016 11:18:41 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalStateException: Result is already complete: succeeded
	at io.vertx.core.impl.FutureImpl.checkComplete(FutureImpl.java:164)
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:108)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:135)
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:23)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$callCompletionHandlerAsync$2(EventBusImpl.java:340)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

It seems easy to reproduce using a verticle that registers addresses on the bus and uses async shutdown.

Digging into the code a bit, I think I see the source of the problem:

When calling EventBusImpl.close here is the code that is run:

```
    public void close(Handler<AsyncResult<Void>> completionHandler) {
      handler.unregister(completionHandler);
      completionHandler.handle(Future.succeededFuture());
    }
```

At this point `completionHandler` is a Future which will be passed to `unregister` and then completed successfully with the next statement.  However, the call to `unregister` eventually leads to an invocation of EventBusImpl.callCompletionHandler which has the following implementation:

```
  protected void callCompletionHandlerAsync(Handler<AsyncResult<Void>> completionHandler) {
    if (completionHandler != null) {
      vertx.runOnContext(v -> completionHandler.handle(Future.succeededFuture()));
    }
  }
```

So we queue an asynchronous execution of the hander with a successful result.  However, since `completionHandler` here is the same future that we we passed to `close` the net result is that the Future is completed twice.

This happens for every Verticle you have deployed, which is why we see so many of these in our logs.

**Comment by vietj** [comment]
Hi,

it has been fixed:

https://github.com/eclipse/vert.x/commit/9736108aa274ef007068f4d782cb03c44c32bb4a

the only side effect is logging

**Comment by sfitts** [comment]
Cool, thanks.
