### ISSUE TITLE
ClassCastException at ReflectionUtils.getComponentType

### ISSUE THREAD

**Issue by lu-ko** [eclipse/vert.x#1715]
ClassCastException occurs during startup of my app. I'm using Vert.x 3.3.3.

```
Exception in thread "main" java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
        at io.vertx.core.cli.impl.ReflectionUtils.getComponentType(ReflectionUtils.java:63)
        at io.vertx.core.cli.annotations.CLIConfigurator.createOption(CLIConfigurator.java:116)
        at io.vertx.core.cli.annotations.CLIConfigurator.define(CLIConfigurator.java:78)
        at io.vertx.core.spi.launcher.DefaultCommandFactory.define(DefaultCommandFactory.java:59)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.register(VertxCommandLauncher.java:127)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.load(VertxCommandLauncher.java:122)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.<init>(VertxCommandLauncher.java:112)
        at io.vertx.core.impl.launcher.VertxCommandLauncher.<init>(VertxCommandLauncher.java:101)
        at io.vertx.core.Launcher.<init>(Launcher.java:41)
```

**Comment by vietj** [comment]
can you give your startup line code that triggers that ?

**Comment by lu-ko** [comment]
It's not a Vert.x bug.

I was using wrong configuration for obfuscation that accidentally results into changed Vert.x code. Technically, obfuscation removed generic signature of the classes, fields, and methods. That caused mentioned problem for `io.vertx.core.impl.launcher.commands.RunCommand#setRedeploy(List)`. Fixed by ProGuard option `-keepattributes Signature`.

I'm sorry for this inconvenience. You can reject and/or close this issue.
