### ISSUE TITLE
NullPointer in sendToSubs

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#1765]
Cloned from vert-x3/vertx-hazelcast#52

**Comment by tsegismont** [comment]
@inno-steffg _commented on 7 Dec 2016_

We're using vertx 3.3.3 in a productive environment clustered with hazelcast.
We are observing the following NullPointerException from time to time:
```
2016-12-07 09:57:08,063 ERROR [vert.x-eventloop-thread-4] [] io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendToSubs(ClusteredEventBus.java:279)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$133(ClusteredEventBus.java:182)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$get$30(HazelcastAsyncMultiMap.java:116)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$16(ContextImpl.java:305)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$18(ContextImpl.java:335)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
	at java.lang.Thread.run(Thread.java:745)
```

I guess, this happens when we're unregistering an eventbus consumer at the same time the sendToSubs is trying to submit a message to it.

**Comment by tsegismont** [comment]
@vietj _commented on 7 Dec 2016_

it seems to be a race condition, what is your version ?

**Comment by tsegismont** [comment]
@inno-steffg _commented on 8 Dec 2016_

Vertx 3.2.1 and vertx 3.3.3 show this problem.
The stack trace above is from Vertx 3.2.1
Version 3.3.3 throws NullPointer at the same place (but another line no):
```
2016-12-08 01:46:18,435 ERROR [vert.x-eventloop-thread-2]  io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.sendToSubs(ClusteredEventBus.java:315)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$4(ClusteredEventBus.java:218)
	at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMultiMap.lambda$get$3(HazelcastAsyncMultiMap.java:116)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:158)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:271)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:440)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tsegismont** [comment]
@tsegismont _commented on 9 Dec 2016_

Could you put together a small reproducer?
