### ISSUE TITLE
3.4.0.Beta1 with netty-tcnative, NoSuchMethodError

### ISSUE THREAD

**Issue by jo5ef** [eclipse/vert.x#1800]
We've been using OpenSSL via netty-tcnative-boringssl-static (1.1.33.Fork23), mostly because ALPN doesn't work with JdkSsl. When trying vertx 3.4.0.Beta1, the following exception is thrown when using `OpenSSLEngineOptions` with `HttpClient`:

    java.lang.NoSuchMethodError: org.apache.tomcat.jni.SSLContext.setCACertificateBio(JJ)Z
    	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:162)
    	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:349)
    	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:334)
    	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:414)
    	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:402)
    	at io.vertx.core.net.impl.SSLHelper.createContext(SSLHelper.java:282)
    	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:417)
    	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:431)
    	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:258)
    	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:230)

The latest netty-tcnative (2.0.0.Beta1) has the same problem.

**Comment by vietj** [comment]
you should use tcnative fork26 instead
