### ISSUE TITLE
In case of NO_HANDLERS, vertx handler executed in wrong context and thread type

### ISSUE THREAD

**Issue by mhstnsc** [eclipse/vert.x#1870]
I am using 3.4.0

Reproducer in this repo: https://github.com/mhstnsc/vertx-tests

Failing code here: https://github.com/mhstnsc/vertx-tests/blob/master/src/test/java/io/vertx/test/threading/WorkerVerticle.java#L25

Run ThreadConsistencyTest.testNoHandlersReply

Explanation of the test:
- clustered vertx
- deploy worker verticle
- Eventbus.send to some whatever address
- completion handler is invoked on wrong context and thread

message before sending

```
2017-03-10 15:18:10,096 DEBUG [vert.x-worker-thread-0] TimersFiredOnOtherThreads:28 - Thread[vert.x-worker-thread-0,5,main] io.vertx.core.impl.WorkerContext@64b679ea
```

message from handler

```
2017-03-10 15:18:10,112 DEBUG [vert.x-eventloop-thread-0] TimersFiredOnOtherThreads:35 - Thread[vert.x-eventloop-thread-0,5,main] io.vertx.core.impl.EventLoopContext@44b5a95a
```

**Comment by mhstnsc** [comment]
This seems to be the fault backtrace

```
2017-03-10 15:47:03,431 DEBUG [vert.x-eventloop-thread-0] ThreadingConsistencyTest:30 - Thread[vert.x-eventloop-thread-0,5,main] io.vertx.core.impl.EventLoopContext@5b90cdab
(NO_HANDLERS,-1) No handlers for address bla
	at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:118)
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:351)
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$sendOrPub$4(ClusteredEventBus.java:248)
	at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:188)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:279)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:324)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by purplefox** [comment]
Seems to be a result of https://github.com/eclipse/vert.x/commit/7f08ec3af9faa10be07c6236cc441e839386efd1

**Comment by tsegismont** [comment]
Tim is right.

This commit is part of the following PR:
https://github.com/eclipse/vert.x/pull/1763

The PR was an attempt to fix the two aspects of
https://github.com/vert-x3/issues/issues/75:
(1) send message instantly when on a worker context
(2) send message instantly when inside executeBlocking

I am going to revert the fix for (1) and keep the fix for (2). Also I'll
add a test to make sure the context in case of a NOHANDLERS error is the
right one.

Thinking again about (1), it's probably not something we should try to fix.
The problem is inherent to worker verticles: you could prevent the handling
of http buffers by blocking too long inside a setPeriodic handler.


2017-03-10 17:07 GMT+01:00 Tim Fox <notifications@github.com>:

**Comment by dongyueceo** [comment]
Hi,
  I'm using  vertx-service-discovery for rpc service. And use vertx-ignite for cluster. The vertx version is 3.5.4.
I also got this exception: NO HANDLER (-1) for address , it appears sometime, not always.
