### ISSUE TITLE
VertxException for already timed out HttpClientRequest if HTTP server closes connection.

### ISSUE THREAD

**Issue by silmeth** [eclipse/vert.x#1909]
Hi, I’ve seen during my tests, that if I send a HTTP request that is timed out, and after that I send another one which gets a response, and then the connection on the server side is closed – then the first request (the one that timed out) calls its `exceptionHandler` with a `VertxException` with a message `Connection was closed`.

**EDIT**: I am seeing this behaviour with Vert.x 3.4.1.

At first I thought that it is due to the client trying to `keepAlive` its connections and reacts with an exception when closed from outside  – but then the exception should rather be thrown on the `vertx` object itself, not on a request that supposedly finished time ago. And then it seems it does not matter if I set `setKeepAlive(true)` or `setKeepAlive(false)`.

[Here is a gist with a test replicating this behaviour.](https://gist.github.com/silmeth/f39ffcda87cf8c4855d70830826d714c)

And here is a log I get from that test:

```
11:38:52.629 [vert.x-eventloop-thread-0] INFO  VertxHttpClientTimeoutTest - Sending request 0.
11:38:52.965 [vert.x-eventloop-thread-0] INFO  VertxHttpClientTimeoutTest - Exception thrown for request 0.
java.util.concurrent.TimeoutException: The timeout period of 300ms has been exceeded while executing GET /test for host localhost
	at io.vertx.core.http.impl.HttpClientRequestBase.timeout(HttpClientRequestBase.java:183) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.http.impl.HttpClientRequestBase.handleTimeout(HttpClientRequestBase.java:168) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.http.impl.HttpClientRequestBase.lambda$setTimeout$0(HttpClientRequestBase.java:126) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:803) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:774) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[vertx-core-3.4.1.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
11:38:52.971 [vert.x-eventloop-thread-0] INFO  VertxHttpClientTimeoutTest - Sending request 1.
11:38:52.982 [vert.x-eventloop-thread-0] INFO  VertxHttpClientTimeoutTest - Received response, status: 200, msg: OK, headers: [X-Req-Num=1, Content-Length=0]
11:38:53.015 [vert.x-eventloop-thread-0] INFO  VertxHttpClientTimeoutTest - Exception thrown for request 0.
io.vertx.core.VertxException: Connection was closed
	at io.vertx.core.http.impl.ClientConnection.handleClosed(ClientConnection.java:408) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335) ~[vertx-core-3.4.1.jar:?]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193) [vertx-core-3.4.1.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:97) [vertx-core-3.4.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:417) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) [netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) [netty-codec-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:256) [netty-codec-http-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:220) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445) [netty-transport-4.1.8.Final.jar:4.1.8.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.8.Final.jar:4.1.8.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
```

Also, [if I comment out the 66th line in the gist (closing the `HttpServer`), and I close `HttpClient` on line 101 instead, the same issue appears](https://gist.github.com/silmeth/f6a42f735d3eef9acff99d1e10eef3c4).

I would expect that if the request has already timed out, it is closed and won’t call its exception nor response handlers anymore. Am I doing something wrong, understanding something wrong, or is it a bug?

**Comment by vietj** [comment]
the exception handler can be called multiple times, we aim in the future to  provide a different model with Handler<AsyncResult<>> where this handler will be called a single time only.
