### ISSUE TITLE
Creating JsonArray from List of non standart objects

### ISSUE THREAD

**Issue by Invizible** [eclipse/vert.x#1923]
When I create a JsonArray like this:

`
JsonArray array = new JsonArray(Arrays.asList(new MySuperClass()));
`

and send this via Event Bus I get java.lang.IllegalStateException: Illegal type in JsonObject: MySuperClass

Here is a part of stacktrace:

`
        at io.vertx.core.json.Json.checkAndCopy(Json.java:125)
	at io.vertx.core.json.JsonArray.copy(JsonArray.java:561)
	at io.vertx.core.json.Json.checkAndCopy(Json.java:106)
	at io.vertx.core.json.JsonObject.copy(JsonObject.java:778)
	at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:49)
	at io.vertx.core.eventbus.impl.codecs.JsonObjectMessageCodec.transform(JsonObjectMessageCodec.java:27)
	at io.vertx.core.eventbus.impl.MessageImpl.<init>(MessageImpl.java:75)
	at io.vertx.core.eventbus.impl.MessageImpl.copyBeforeReceive(MessageImpl.java:81)
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverToHandler(EventBusImpl.java:494)
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:370)
	at io.vertx.core.eventbus.impl.EventBusImpl.deliverMessageLocally(EventBusImpl.java:347)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPub(EventBusImpl.java:320)
	at io.vertx.core.eventbus.impl.EventBusImpl$SendContextImpl.next(EventBusImpl.java:450)
	at io.vertx.core.eventbus.impl.EventBusImpl.sendOrPubInternal(EventBusImpl.java:418)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:94)
	at io.vertx.core.eventbus.impl.EventBusImpl.send(EventBusImpl.java:89)
`

I think JsonArray class can either check type of elements in the list or perform JsonObject.mapFrom() automatically under the hood.

BTW it's not reproducible in Clustered Event Bus

**Comment by tsegismont** [comment]
When the event bus is not clustered, the message body is simply copied
before delivery. When it is clustered, the message body is converted to
json before sending. I guess your class is serializable with Jackson?

Have you started a PR ?

2017-04-04 14:06 GMT+02:00 Alex Korobko <notifications@github.com>:

**Comment by Invizible** [comment]
@tsegismont I didn't, but I can fix it and submit PR.

**Comment by Invizible** [comment]
@tsegismont What fix would you suggest? serialize into json objects all elements of given list inside JsonArray?

**Comment by tsegismont** [comment]
Not sure yet.

In the meantime, can you try this:

`JsonArray array = new JsonArray().add(JsonObject.mapFrom(new
MySuperClass()));`


2017-04-04 14:39 GMT+02:00 Alex Korobko <notifications@github.com>:

**Comment by Invizible** [comment]
@tsegismont That's what I do now)

**Comment by tsegismont** [comment]
I believe it all boils down to whether we want to the JsonArray(List)
constructor to be strict or not. Strict meaning applying the same
constraints as JsonArray.add(Object).

So instead of assigning the list param to the field, we'd iterate over the
values and invoke Json.checkAndCopy(value, false)

2017-04-04 16:27 GMT+02:00 Alex Korobko <notifications@github.com>:

**Comment by tsegismont** [comment]
I had a second thought about this. So you have a Jackson-annotated POJO and you want to send a list of objects over the event bus, correct? Then the good way to do this is as follows:

```java
    List<MyJacksonPojo> values = new ArrayList<>();
    values.add(pojo1);
    values.add(pojo2);
    Buffer json = Json.encodeToBuffer(values);
   eventBus.send(json);
```

The conversion and sending are efficient and you don't need to create a `JsonArray` wrapper.

**Comment by mystdeim** [comment]
Buffer json = Json.encodeToBuffer(values);
How to decode it back?

**Comment by tsegismont** [comment]
This should do:

```java
TypeReference ref = new TypeReference<List<MyJacksonPojo>>() { };
List<MyJacksonPojo> values = Json.decodeValue(json, ref);
```
