### ISSUE TITLE
vertx throws "IllegalStateException: Failed to create cache dir" though "vertx.disableFileCaching=true"

### ISSUE THREAD

**Issue by m0** [eclipse/vert.x#1931]
I am using vertx for a small web service that should run without disk write access.
Sadly vertx insists in having a writeable cache directory though I set "vertx.disableFileCaching=true":
java.lang.IllegalStateException: Failed to create cache dir
	at io.vertx.core.impl.FileResolver.setupCacheDir(FileResolver.java:293)
	at io.vertx.core.impl.FileResolver.<init>(FileResolver.java:86)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:175)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:142)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:42)
	at io.vertx.core.Vertx.vertx(Vertx.java:90)
	at com.sipgate.litc.HealthService.start(HealthService.java:18)
	at com.sipgate.litc.Main.main(Main.java:20)

I had a quick look at FileResolver.java and would expect any cacheFile handling to be skipped when ENABLE_CACHING is false, but as far as I understand the code, the public interface of at least FileResolver would have to change.
Before digging deeper into the code and developing a patch, I would like to know if changing the behaviour to match what I expect, is appreciated. 

Do I miss something?

**Comment by tsegismont** [comment]
You should set "vertx.disableFileCPResolving" to true instead.

2017-04-10 10:14 GMT+02:00 Moritz Maisel <notifications@github.com>:

**Comment by m0** [comment]
Oh, obviously I misssed that flag when I looked over the code. Thank's for the fast response! :+1:
