### ISSUE TITLE
Intermittent failure in Http1xTest.testCloseTheConnectionAfterResetBeforePipelinedResponseReceived

### ISSUE THREAD

**Issue by tsegismont** [eclipse/vert.x#1938]
```
Starting test: Http1xTest#testCloseTheConnectionAfterResetBeforePipelinedResponseReceived 
io.vertx.core.VertxException: Connection was closed
java.lang.IllegalStateException: Timed out in waiting for test complete
	at io.vertx.test.core.AsyncTestBase.await(AsyncTestBase.java:131)
	at io.vertx.test.core.AsyncTestBase.await(AsyncTestBase.java:119)
	at io.vertx.test.core.Http1xTest.testCloseTheConnectionAfterResetBeforeResponseReceived(Http1xTest.java:3313)
	at io.vertx.test.core.Http1xTest.testCloseTheConnectionAfterResetBeforePipelinedResponseReceived(Http1xTest.java:3218)
```

I can reproduce on my machine with `@Repeat`

**Comment by tsegismont** [comment]
See https://vertx.ci.cloudbees.com/job/vert.x3-core/5509/testReport/junit/io.vertx.test.core/Http1xTest/testCloseTheConnectionAfterResetBeforePipelinedResponseReceived/

**Comment by Sammers21** [comment]
when clicking on the link

![image](https://user-images.githubusercontent.com/16746106/30980613-55b6b058-a48a-11e7-9c59-db306a0d5df2.png)

**Comment by vietj** [comment]
can you try to reproduce it ? I believe this was fixed by a recent commit a about message ordering in a channel

**Comment by vietj** [comment]
fixing this, reopen if it shows up again but it should be fixed AFAIK
