### ISSUE TITLE
Add support for max lifetime on HttpClient pool connections

### ISSUE THREAD

**Issue by jasoncopeland** [eclipse/vert.x#1977]
Add support to HttpClient pooled connections such that a keep-alive connection is only used up to a specified maximum amount of time before being closed and recycled.  This would allow for clean recycling of IP by first removing it from DNS, such that you only need to wait for DNS TTL + HttpClient max connection life time.

The connection could either be checked when the connection is obtained from the pool or an existing/new background maintenance thread could scan through existing connections and closing any any that are too old.  While checking when obtaining the connection from the pool is sufficient, proactively closing would allow the server side to detect that all connections are closed, and thus could recycle itself earlier if it detected it didn't have any current active connections.

This is in support for thread here: https://groups.google.com/forum/#!topic/vertx/4J0RW_buAtU

**Comment by vietj** [comment]
this has been implemented

**Comment by mkulak** [comment]
> this has been implemented
How can I configure it?

**Comment by vietj** [comment]
@mkulak with HttpClientOptions, its called keepAliveTimeout and http2KeepAliveTimeout

**Comment by iamitpatil1993** [comment]
What is vert.x fix version for this issue?

**Comment by vietj** [comment]
@iamitpatil1993 3.5.2, here is the actual issue https://github.com/eclipse-vertx/vert.x/issues/2326

**Comment by jasoncopeland** [comment]
Though closed to be clear, I don't see this support.  This is about defining the max time a connection can be used in total.  If you have a single connection, and you make a continuous number of requests it will remain open, for as long as it can.  I would like to identify a max total age of a connection..

**Comment by vietj** [comment]
@jasoncopeland you are right. It is not yet implemented, in the mean time you can set a client `connectionHandler` that is called when a connection is created and call `shutdown` on the connection with the max lifetime you want to give. This will set a timer that will close the connection after a while and when it is unused

**Comment by narras-oss** [comment]
We tried this approach and when there is a lot of traffic, calling shutdown(60 * 1000) on a connection results in in-flight requests failing immediately (doesn't wait fro 60 seconds). How can we avoid this? 
Is there a way to gracefully remove the connection out of the connection pool so no more new requests are sent on the connection but current requests are allowed to finish

**Comment by vietj** [comment]
@narras-oss you can use `HttpConnection#shutdown` to achieve this

**Comment by narras-oss** [comment]
@vietj  The vertx http client we use reaches out a DNS endpoint that has short TTL and can change often. So we used this workaround to set max lifetime of a connection to approx. 5 minutes.

httpClient.connectionHandler(connection -> scheduleShutdown(() -> connection.shutdown(60 * 1000), 5mins));

We attach a connection handler to httpClient and schedule the call to "connection.shutdown(60 * 1000)" after 5mins.

When we applied this fix in production, we started noticing occasional failures (a few every day) because we have jeavy traffic in production. Some of the stacktraces are below. 


```
Caused by: io.netty.handler.codec.http2.Http2Exception: Attempted to create stream id 6131 after connection was closed
	at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:108)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.checkNewStreamAllowed(DefaultHttp2Connection.java:906)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:751)
	at io.netty.handler.codec.http2.DefaultHttp2Connection$DefaultEndpoint.createStream(DefaultHttp2Connection.java:671)
	at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.createStream(Http2ClientConnection.java:549)
	at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.writeHeaders(Http2ClientConnection.java:524)
	at io.vertx.core.http.impl.Http2ClientConnection$StreamImpl.lambda$writeHead$0(Http2ClientConnection.java:492)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
	at io.vertx.core.impl.EventLoopContext.lambda$emit$1(EventLoopContext.java:57)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
```
We were able to reproduce this as well if we continuously send requests to a local http server (the endpoint does nothing and responds very quickly). 

We are now trying to call connection.goAway(0) instead of shutdown() - it seems to work better but we are not sure the connection will be closed properly if we do so.

**Comment by vietj** [comment]
do you know if that happens before or after the time limit ?
