### ISSUE TITLE
better error reporting of application logic within stacktrace

### ISSUE THREAD

**Issue by nimo23** [eclipse/vert.x#2011]
I have some code executed within a vertx:
```
@Override
public void start(Future<Void> fut) throws IOException {

vertx.setPeriodic(period, l -> {
httpClient
.requestAbs(HttpMethod.GET, uri)
.handler(response -> {
  response.bodyHandler(totalBuffer -> {
// in this place I call my application logic
..
.exceptionHandler(e -> {		
log.error("Received exception: {} | {}", e.getMessage(), e.getCause());
e.printStackTrace();
})
.end();
});
```

and when starting the vertx then this stacktrace occurs:

```
[INFO] (20:03:06.377) vert.x-eventloop-thread-0 (MyVertx:151) | Received exception: Connection was closed | null
[INFO] io.vertx.core.VertxException: Connection was closed
[INFO] 	at io.vertx.core.http.impl.ClientConnection.handleClosed(ClientConnection.java:408)
[INFO] 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
[INFO] 	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
[INFO] 	at io.vertx.core.net.impl.VertxHandler.channelInactive(VertxHandler.java:97)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
[INFO] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[INFO] 	at io.netty.handler.codec.http.HttpContentDecoder.channelInactive(HttpContentDecoder.java:205)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
[INFO] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:417)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
[INFO] 	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:256)
[INFO] 	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:220)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
[INFO] 	at io.netty.handler.logging.LoggingHandler.channelInactive(LoggingHandler.java:167)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360)
[INFO] 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325)
[INFO] 	at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:861)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:225)
[INFO] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:246)
[INFO] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:232)
[INFO] 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908)
[INFO] 	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744)
[INFO] 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasksFrom(SingleThreadEventExecutor.java:379)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:354)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor.confirmShutdown(SingleThreadEventExecutor.java:678)
[INFO] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:455)
[INFO] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[INFO] 	at java.lang.Thread.run(Thread.java:745)
```

After searching, I found the reason why my vertx throws this stacktrace: Within my application logic, I have called MyEnums.valueOf("TEST") which should return "MyEnums.TEST". However, I did not have the Enum "TEST" declared before, so vertx closed with a stacktrace. After putting the Enum "TEST" within my MyEnums, vertx starts normal and it works.

**The bad thing is, why does the stacktrace does not show the error of my application logic?** 
Because of the event-loop? Would be nice if I can trace my errors within the stacktrace.

**Comment by Sammers21** [comment]
@nimo23 , it seems that your code does not look so good....

Can you improve code formatting?

Thanks!

**Comment by tsegismont** [comment]
Please use the Vert.x forum for usage questions. Not everyone in the community is subscribed to the GitHub repositories.

See vertx.io/community
