### ISSUE TITLE
Vertx-web-js : SockJSHandler error while calling bridge function

### ISSUE THREAD

**Issue by Wano-k** [eclipse/vert.x#2054]
I'm on Windows and tried to launch a `server.js` in command line and in IDE with maven dependencies, but both failed with the same error.

Here is the server:

```js
var Router = require("vertx-web-js/router");
var SockJSHandler = require("vertx-web-js/sock_js_handler");
var router = Router.router(vertx);

var options = {};
var sockJSHandler = SockJSHandler.create(vertx).bridge(options);
router.route("/eventbus/*").handler(sockJSHandler.handle);
```

The command lines (using vertx 3.4.2 full version):
```
>java -version
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode)
```

```
>vertx run server.js
javax.script.ScriptException: TypeError: Cannot call undefined in vertx-web-js/sock_js_handler.js at line number 87
        at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:455)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:439)
        at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptE
ngine.java:401)
       ...
```

The server is perfectly working until I use `.bridge(options);`.

**Comment by Wano-k** [comment]
I tried with vertx 3.3.2 and my code is working.

**Comment by pmlopes** [comment]
This issue was moved to vert-x3/vertx-web#664
