### ISSUE TITLE
ConnectionManager: Connection pool always reached max wait queue size

### ISSUE THREAD

**Issue by troopson** [eclipse/vert.x#2060]
My project use webclient to make http request.  When under a large number of request running for hours, it's always reach a wrong state at end, that no request will send indeed while always logs with: Connection pool reached max wait queue size.

here is my code:
[Node.java](https://github.com/troopson/etagate/blob/master/src/main/java/org/etagate/app/node/Node.java)

I dumped the stack and found the connCount is equals maxPoolSize while no connect available. so I think maybe the Http1xPool can‘t create new connection because connCount is not really response to the connection pool size. 

here is some stacktrace:

```java

116310 [vert.x-eventloop-thread-2] INFO  org.etagate.app.node.Node - auth, GET http://172.21.9.26:8080/auth/shortstring
116310 [globalEventExecutor-1-1] WARN  i.n.util.concurrent.DefaultPromise - An exception was thrown by io.vertx.core.net.impl.ChannelProvider$$Lambda$85/1186466417.operationComplete()
java.lang.IllegalStateException: Uh oh! Event loop context executing with wrong thread! Expected null got Thread[globalEventExecutor-1-1,5,main]
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:316)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
        at io.vertx.core.http.impl.ConnectionManager$ConnQueue.connectionFailed(ConnectionManager.java:373)
        at io.vertx.core.http.impl.ConnectionManager$ConnQueue.access$1600(ConnectionManager.java:197)
        at io.vertx.core.http.impl.ConnectionManager$ChannelConnector.lambda$connect$2(ConnectionManager.java:549)
        at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:42)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
        at io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run(GlobalEventExecutor.java:233)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

```

The reason cause the fail of create connection.

```java

116230 [vert.x-acceptor-thread-0] WARN  i.n.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in t
he pipeline did not handle the exception.
java.io.IOException: Too many open files
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:110)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:107)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:107)
        
```

The following is my guess.

When call createNewConnection, the connCount++， but the connection create failed，then function connectionFailed was called where connectionClosed() will be executed in context.executeFromIO, so connCount can decrease back. 
context.executeFromIO will check the current Thread ，if not VertxThread， cause an exception， that may lead to a result: the connectionClose would not be called and connCount can not decrease back，This means that the connCount will increased without add a new connection in the connection pool, at last, no connection can be poll, no connection will be create, all waiter go to the queue.

**Comment by vietj** [comment]
so to sum-up you are saying that in case of _Too many open files_, that is raised by the `GlobalEventExecutor` thread which is rejected by `ContextImpl` and this causes the leak in the pool.

**Comment by vietj** [comment]
what is not clear is that the _Too many open files_ seems to be a server issue (`ServerSocketChannelImpl`), can you elaborate ?

**Comment by tsegismont** [comment]
The "too many open files" issue is a system limit which can be changes
globally or per user. Increasing it might be beneficial but first you need
to determine why the limit was reached. The web client has a max pool size.
How is yours set up ? The web client connections might not be the culprits
if something else in your system opens a lot of files/connections.

Could you post some code to see how you use the web client ?
The IllegalStateException indicates the webclient is used outside of its
creation context.

All that said, the web client should be able to manage failures to create a
connection so if you can put together a reproducer it should be fixed.



2017-07-19 10:23 GMT+02:00 Julien Viet <notifications@github.com>:

**Comment by vietj** [comment]
@tsegismont the `GlobalEventExecutor` callback should be handled gracefully by Vert.x though, so I would like to understand more how this is related to the case

**Comment by troopson** [comment]
@vietj  I'm not really sure what the real reason is，just try to figure it out.   

@tsegismont  you can see the code at [code](https://github.com/troopson/etagate/blob/master/src/main/java/org/etagate/app/node/Node.java)

**Comment by troopson** [comment]
It is not easy to reproducing the wrong thread error， and I found a mistake in my code, my counter is not accordant to the waiters， that lead to the wrong state，maybe it is not a issue in ConnectionManager，so I will close the issue first，If it occurs again  I will reopen it.  thanks @vietj  @tsegismont
