### ISSUE TITLE
IllegalStateException when using sendStream

### ISSUE THREAD

**Issue by mmatecki** [eclipse/vert.x#2088]
Hi,
Vert.x 3.4.2 with WebClient
I've got issue with using sendStream to forward request to another service. It results in ``IllegalStateException: Request has already been read``

Code to reproduce:
```
public class Service1 extends AbstractVerticle {
    @Override
    public void start() throws Exception {
        Router router = Router.router(vertx);
        router.post("/").handler(routingContext -> {
            WebClient webClient = WebClient.create(vertx);
            webClient.postAbs("http://localhost:10001/")
                    .sendStream(routingContext.request(), ar -> System.out.println("R: "+ar.result()));
        });
        vertx.createHttpServer()
                .requestHandler(router::accept)
                .listen(10000);
    }
}
```

Result:
```
Aug 03, 2017 5:04:23 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.IllegalStateException: Request has already been read
 at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:426)
 at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:206)
 at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:42)
 at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:19)
 at io.vertx.core.streams.impl.PumpImpl.stop(PumpImpl.java:97)
 at io.vertx.core.streams.impl.PumpImpl.stop(PumpImpl.java:42)
 at io.vertx.ext.web.client.impl.HttpRequestImpl.lambda$send$12(HttpRequestImpl.java:342)
 at io.vertx.core.http.impl.HttpServerRequestImpl.handleEnd(HttpServerRequestImpl.java:406)
 at io.vertx.core.http.impl.ServerConnection.handleEnd(ServerConnection.java:297)
 at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:441)
 at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:131)
 at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:673)
 at io.vertx.core.http.impl.HttpServerImpl$ServerHandler.doMessageReceived(HttpServerImpl.java:580)
 at io.vertx.core.http.impl.VertxHttpHandler.lambda$channelRead$0(VertxHttpHandler.java:71)
 at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
 at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
 at io.vertx.core.http.impl.VertxHttpHandler.channelRead(VertxHttpHandler.java:71)
 at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:122)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
 at java.lang.Thread.run(Thread.java:748)
```
Link to post at Google Group: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/vertx/srXkOOK8tj0/SXPuo7J8AAAJ

Thanks,
Maciek.

**Comment by vietj** [comment]
I think the issue should now be solved, it was because we set null handler on stop and setting null handler should not make this behavior

**Comment by vietj** [comment]
I will check

**Comment by vietj** [comment]
actually there is a test for this in Vert.x Core : HttpTest#testClearHandlersOnEnd

**Comment by vietj** [comment]
not setting a fix version as it was probably fixed before
