### ISSUE TITLE
Problem handling SSL Exceptions with ClientAuth.REQUIRED

### ISSUE THREAD

**Issue by dachaac** [eclipse/vert.x#2104]
If one set NetServer instance to require SSL Client Certificate authentication and client does not send it netty throws exception that vert.x does not handle cleanly even if one registers exception handler for NetSocket.

Initially encountered this issue while writing SSL test cases for vertx-mqtt.

If one changes code snippet to use ClientAuth.REQUEST then you can see openssl's s_client nicely connected.

What I would have expected:
- No exception shown in logs
- Ability to catch failure case for unit tests
- Socket closed is kinda OK but now it was completely invisible for application thus hard to make unit tests for it

Code snippet:
```
        NetServerOptions netServerOptions = new NetServerOptions()
                .setPfxKeyCertOptions(new PfxOptions()
                        .setPath("server.p12")
                        .setPassword("password"))
                .setTrustOptions(new PemTrustOptions()
                        .addCertPath("ca.crt"))
                .setSsl(true)
                .setClientAuth(ClientAuth.REQUIRED)
                ;
        NetServer server = vertx.createNetServer(netServerOptions);
        server.connectHandler(socket -> {
            socket.closeHandler(v -> {
                System.out.println("The socket has been closed");
            });
            socket.handler(buffer -> {
                System.out.println("I received some bytes: " + buffer.length());
            });
            socket.exceptionHandler(e -> {
                System.out.println("got exception\r\n");
            });
            System.out.println("Client connected: " + socket.remoteAddress() + "\r\n");
            socket.write("Welcome to the Service\r\n");
        });

        server.listen(1234, "localhost", res -> {
            if (res.succeeded()) {
                System.out.println("Server is now listening!");
            } else {
                System.out.println("Failed to bind!");
            }
        });
```

Test command with openssl:
```
$ openssl s_client -connect localhost:1234 -tls1
CONNECTED(00000003)
depth=0 /C=FI/O=Something/CN=localhost
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 /C=FI/O=Something/CN=localhost
verify error:num=27:certificate not trusted
verify return:1
depth=0 /C=FI/O=Something/CN=localhost
verify error:num=21:unable to verify the first certificate
verify return:1
31628:error:14094412:SSL routines:SSL3_READ_BYTES:sslv3 alert bad certificate:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s3_pkt.c:1145:SSL alert number 42
31628:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s3_pkt.c:566:
```

Note: had to add -tls1 otherwise following was generated:
```
$ openssl s_client -connect localhost:1234
CONNECTED(00000003)
31681:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-64.50.6/src/ssl/s23_clnt.c:618:

And in log:
Aug 26, 2017 9:10:11 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: SSLv2Hello is disabled
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
...
```

Test snippet log:
```
Starting vert.x application...
Aug 26, 2017 12:02:03 AM io.vertx.core.impl.launcher.commands.Watcher
fb9ae8fe-4e51-42f5-9f08-21b375509244-redeploy
INFO: User command terminated with status 0
Aug 26, 2017 12:02:03 AM io.vertx.core.impl.launcher.commands.Watcher
INFO: Redeployment done in 1426 ms.
Server is now listening!
Aug 26, 2017 12:02:03 AM io.vertx.core.impl.launcher.commands.VertxIsolatedDeployer
INFO: Succeeded in deploying verticle
Aug 26, 2017 12:03:44 AM io.vertx.core.net.impl.NetServerImpl
SEVERE: Client from origin /127.0.0.1:61390 failed to connect over ssl: javax.net.ssl.SSLHandshakeException: null cert chain
Aug 26, 2017 12:03:44 AM io.netty.channel.DefaultChannelPipeline onUnhandledInboundException
WARNING: An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: null cert chain
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:341)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:642)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:565)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:479)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:441)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1478)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.netty.handler.ssl.SslHandler$SslEngineType$2.unwrap(SslHandler.java:223)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1117)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1039)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 15 more
Caused by: javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:304)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:292)
	at sun.security.ssl.ServerHandshaker.clientCertificate(ServerHandshaker.java:1862)
	at sun.security.ssl.ServerHandshaker.processMessage(ServerHandshaker.java:233)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:966)
	at sun.security.ssl.Handshaker$1.run(Handshaker.java:963)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1416)
	at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1256)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1169)
	... 17 more
```

**Comment by dachaac** [comment]
In order to remove the exception being displayed in the log it kinda feels that one would need to add handler to netty's pipeline as last or after netty's SslHandler and then capture SSLExceptions and somehow handle them in NetServerImpl.

**Comment by vietj** [comment]
I think this is normal, the client is not able to connect as the SSL handshake fails, so the connect handler is not called at all.

**Comment by vietj** [comment]
one way to handle this case would be to not set TLS but use startTLS after connect in the connect handler, something like:

```
    server = vertx.createNetServer(new NetServerOptions().setTrustOptions(Trust.SERVER_JKS.get()).setKeyStoreOptions(Cert.SERVER_JKS.get())
      .setSsl(false).setClientAuth(ClientAuth.REQUIRED).setPort(1234));
    server.connectHandler(so -> {
      System.out.println("connected");
      so.exceptionHandler(err -> {
        System.out.println("upgrade failed");
      });
      so.upgradeToSsl(v -> {
        System.out.println("upgraded");
      });
    });
    startServer();
    client = vertx.createNetClient(new NetClientOptions().setSsl(true).setTrustOptions(Trust.SERVER_JKS.get()));
    client.connect(1234, "localhost", ar -> {
      System.out.println("client " + ar.succeeded());
    });
```

**Comment by vietj** [comment]
I'm going to close this issue as it does not seem to be a Vertx bug

**Comment by dachaac** [comment]
What is your take on unhandled exception being thrown? In my philosophy any exception being thrown in logs is subject of coding error and needs analysis why it is happening.

In this case it is reasonable to expect that socket is just silently closed without generating exception.

Do you think this is problem in netty and it should be handled there and not in vert.x core?

**Comment by vietj** [comment]
it's an exception that is similar to handling abnormal TCP connection with a RST that prints a connection reset in the logs

you don't want to deal with it, but you might not want to ignore it.
