### ISSUE TITLE
Get NullPointerException when create shared JDBCClient with vertx core 3.4.2

### ISSUE THREAD

**Issue by anawu2006** [eclipse/vert.x#2139]
When creating a shared JDBCClient in vertx core 3.4.2 version with:
```
JDBCClient jdbcClient = JDBCClient.createShared(vertx, new JsonObject()
                        .put("url", "jdbc:mysql://localhost:3306/mydb")
                        .put("user", "user")
                        .put("password", "pwd")
                        .put("driver_class", "com.mysql.cj.jdbc.Driver")
                        .put("max_pool_size", 30));
```

I got the exception:
```
java.lang.NullPointerException
	at io.vertx.ext.jdbc.impl.JDBCClientImpl$DataSourceHolder.ds(JDBCClientImpl.java:213)
	at io.vertx.ext.jdbc.impl.JDBCClientImpl.<init>(JDBCClientImpl.java:88)
	at io.vertx.ext.jdbc.JDBCClient.createShared(JDBCClient.java:79)
	at com.obietel.upp.db.LcrDBController.init(LcrDBController.java:47)
	at com.obietel.upp.db.LcrDBController.<init>(LcrDBController.java:33)
	at com.obietel.upp.callplan.CallPlanManageVerticle.init(CallPlanManageVerticle.java:80)
	at com.obietel.upp.BaseVerticle.start(BaseVerticle.java:33)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:477)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

But it runs well in vertx core 3.4.1.
Anybody has idea about how to fix it for 3.4.2 ? Thanks.

**Comment by EmadAlblueshi** [comment]
Hi @anawu2006 

I think the issue should be opened here https://github.com/vert-x3/vertx-jdbc-client

Thanks!

**Comment by yassirh** [comment]
Are you sure that the vertx instance you are using is not null? If so try : 

```
JDBCClient jdbcClient = JDBCClient.createShared(Vertx.vertx(), new JsonObject()
                        .put("url", "jdbc:mysql://localhost:3306/mydb")
                        .put("user", "user")
                        .put("password", "pwd")
                        .put("driver_class", "com.mysql.cj.jdbc.Driver")
                        .put("max_pool_size", 30));
```

**Comment by pmlopes** [comment]
And are you including the MySQL driver in your pom? The best is to provide a reproducer

**Comment by anawu2006** [comment]
@yassirh Yes, vertex instance is not null for sure. 
@pmlopes Yes. MySQL driver is in my pom.
@EmadAlblueshi OK. I will open this issue in https://github.com/vert-x3/vertx-jdbc-client
Thanks so much for all of your replying.

**Comment by deshrajsingh** [comment]
@anawu2006 just make sure the vertx-jdbc-client dependency version and other vertx dependencies versions are same. and if doesn't work try 3.5.0 version of dependencies.
