### ISSUE TITLE
weird problem in clustered mode of Hazelcast

### ISSUE THREAD

**Issue by sephrouse** [eclipse/vert.x#2161]
an IllegalStateException occurred when accessing url http://localhost:8080/ .

Unexpected exception in route
java.lang.IllegalStateException: Request has already been read
        at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:426)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:206)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:42)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:66)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:40)
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
        at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$0(SessionHandlerImpl.java:127)
        at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$2(SessionHandlerImpl.java:155)
        at io.vertx.ext.web.sstore.impl.ClusteredSessionStoreImpl.lambda$null$0(ClusteredSessionStoreImpl.java:73)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)

the issue could be reproduced by the following code:
    private Future<Void> createWebServer() {
        Future<Void> cwsFuture = Future.future();

        Router router = Router.router(vertx);
        
        router.route().handler(CookieHandler.create());
        **SessionStore ss = ClusteredSessionStore.create(vertx);
        SessionHandler sh = SessionHandler.create(ss);
        router.route().handler(sh);
        router.route().handler(BodyHandler.create());**

        // home page
        router.get("/").handler(this::Index);

        // static resources
        router.route("/public/*").handler(StaticHandler.create("webroot/static"));

        vertx
                .createHttpServer()
                .requestHandler(router::accept)
                .listen(config().getInteger("http.port", 8080), wsRes -> {
                    if(wsRes.succeeded()) {
                        LOGGER.info("WebServerVerticle has been started successfully.");
                        cwsFuture.complete();
                    }else{
                        LOGGER.error("Failed to createHttpServer.");
                        cwsFuture.fail(wsRes.cause());
                    }
                });

        return cwsFuture;
    }

    private void Index(RoutingContext rc) {
        System.out.println("in index. " + Thread.currentThread().getName());
        rc.response().sendFile("webroot/index.html");
    }

please pay attention in above bold code. the web service seems good and could work when I put the **router.route().handler(BodyHandler.create());** in front of **router.route().handler(CookieHandler.create());** .
the web service works very well, no exception occurs.

is there anyone who could tell me why? I could not find any suggestion in the document that the BodyHandler.create() should be called before calling SessionHandler.create().

thanks in advance.

**Comment by sephrouse** [comment]
the version is 3.4.2

**Comment by tsegismont** [comment]
What's the connection with the Hazelcast cluster manager?

2017-10-06 10:57 GMT+02:00 sephrouse <notifications@github.com>:

**Comment by sephrouse** [comment]
I used one computer to start the cluster in main verticle by command java -jar xxxxx-fat.jar -cluster. there was no other computers to execute the above cmd to join the cluster.

**Comment by tsegismont** [comment]
OK. Can you reproduce without clustering enabled then? It seems to me the
issue really is with the order of Vert.x Web handlers. I can't see the
connection with clustering so the thread title is confusing

2017-10-07 16:31 GMT+02:00 sephrouse <notifications@github.com>:

**Comment by sephrouse** [comment]
OK. I will take a try to reproduce the issue in non-clustered mode.

**Comment by sephrouse** [comment]
sorry for confusing you. the strange stuff is the program works well when the **router.route().handler(BodyHandler.create());** is in front of **router.route().handler(CookieHandler.create());** .

the issue occurs when **router.route().handler(BodyHandler.create());** is after **router.route().handler(sh);**

**Comment by tsegismont** [comment]
@sephrouse sorry but your last message is still confusing. You say the program works well when 2 handlers are added in a particular order. Then you say it doesn't when 2 other handlers are in another order.

I don't know what `sh` does, but `BodyHandler` should be definitely be added before any user handler.

Please create a proper reproducer on GitHub otherwise we can only guess.

**Comment by sephrouse** [comment]
sh is as follows:
**SessionStore ss = ClusteredSessionStore.create(vertx);
SessionHandler sh = SessionHandler.create(ss);
router.route().handler(sh);**

sorry for confusing you. it should be my mistake if BodyHandler has to be added before clustered session handler. however, the code goes without any problem while BodyHandler is being added after local session handler in non-clustered verticle.

**Comment by tsegismont** [comment]
Please provide a full example to reproduce. Thank you

2017-10-09 15:43 GMT+02:00 sephrouse <notifications@github.com>:

**Comment by sephrouse** [comment]
2 AbstractVerticle source files.

DeploymentVerticle.java
package com.example.reproduce;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;
import io.vertx.core.spi.cluster.ClusterManager;
import io.vertx.spi.cluster.hazelcast.HazelcastClusterManager;

public class DeploymentVerticle extends AbstractVerticle {

    @Override
    public void start() {
        ClusterManager mgr = new HazelcastClusterManager();
        VertxOptions opt = new VertxOptions().setClusterManager(mgr).setClustered(true);

        Vertx.clusteredVertx(opt, clusteredRes -> {
            if(clusteredRes.succeeded()) {
                Vertx vertx = clusteredRes.result();

                DeploymentOptions webServerVerticleOpt = new DeploymentOptions().setConfig(config()).setInstances(config().getInteger("web", 4));

                vertx.deployVerticle("com.example.reproduce.WebServerVerticle", webServerVerticleOpt, dpyRes -> {
                    if(!dpyRes.succeeded()) {
                        System.out.println("failed to deploy web server verticle.");
                        vertx.close();
                    }
                });
            }else{
                System.out.println("failed to be clustered vertx.");
                vertx.close();
            }
        });
    }
}

WebServerVerticle.java

package com.example.reproduce;

import io.vertx.core.*;
import io.vertx.ext.web.Router;
import io.vertx.ext.web.RoutingContext;
import io.vertx.ext.web.handler.BodyHandler;
import io.vertx.ext.web.handler.CookieHandler;
import io.vertx.ext.web.handler.SessionHandler;
import io.vertx.ext.web.sstore.ClusteredSessionStore;


public class WebServerVerticle extends AbstractVerticle {
    @Override
    public void start(Future<Void> webFuture) {
        Future<Void> wsFuture = createWebServer();

        wsFuture.setHandler(cwsRes -> {
            if(cwsRes.succeeded()) {
                webFuture.complete();
            }else{
                webFuture.fail(cwsRes.cause());
            }
        });

    }

    private Future<Void> createWebServer() {
        Future<Void> cwsFuture = Future.future();

        Router router = Router.router(vertx);
        router.route().handler(CookieHandler.create());
        router.route().handler(SessionHandler.create(ClusteredSessionStore.create(vertx)));
        router.route().handler(BodyHandler.create());

        router.get("/").handler(this::Home);

        vertx
                .createHttpServer()
                .requestHandler(router::accept)
                .listen(config().getInteger("http", 8080), wsRes -> {
                    if(wsRes.succeeded()) {
                        cwsFuture.complete();
                    }else{
                        System.out.println("failed to start web server.");
                        cwsFuture.fail(wsRes.cause());
                    }
                });

        return cwsFuture;
    }

    private void Home(RoutingContext rc) {
        rc.response().end("is there any exceptions?");
    }
}

after having done all above. execute **_mvn clean package_** to generate a fat jar.
start the jar file like the following
D:\project\java\idea\reproduce>java -jar target\reproduce-1.0-SNAPSHOT-fat.jar

open the browser like chrome, enter localhost:8080 to make the webserververticle execute Home function. if the issue didn't occur, refresh the page. then, got the exception on stdout like this:
Oct 10, 2017 9:22:13 AM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
java.lang.IllegalStateException: Request has already been read
        at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:426)
        at io.vertx.core.http.impl.HttpServerRequestImpl.handler(HttpServerRequestImpl.java:206)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.handler(HttpServerRequestWrapper.java:42)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:66)
        at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:40)
        at io.vertx.ext.web.impl.RouteImpl.handleContext(RouteImpl.java:217)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:78)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:118)
        at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$handle$0(SessionHandlerImpl.java:127)
        at io.vertx.ext.web.handler.impl.SessionHandlerImpl.lambda$doGetSession$2(SessionHandlerImpl.java:155)
        at io.vertx.ext.web.sstore.impl.ClusteredSessionStoreImpl.lambda$null$0(ClusteredSessionStoreImpl.java:73)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:287)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Unknown Source)

**Comment by tsegismont** [comment]
Actually this behavior of the BodyHandler is documented in the "Request
body handling" section of the Vert.x Web docs:

"The usage of this handler requires that it is installed as soon as
possible in the router since it needs to install handlers to consume the
HTTP request body and this must be done before executing any async call."

If you install it after other handlers, it will be triggered only when they
invoke routingContext.next() (see
http://vertx.io/docs/vertx-web/java/#_handling_requests_and_calling_the_next_handler
)

So chances are high that the events captured by the BodyHandler have
already been handled. Hence the "Request has already been read"

2017-10-10 3:25 GMT+02:00 sephrouse <notifications@github.com>:
