### ISSUE TITLE
Got a NullPointerException when event bus was under heavy load

### ISSUE THREAD

**Issue by gjroylance** [eclipse/vert.x#2168]
Oct 06, 2017 10:14:49 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.NullPointerException
        at io.vertx.core.eventbus.impl.clustered.ConnectionHolder.connected(ConnectionHolder.java:125)
        at io.vertx.core.eventbus.impl.clustered.ConnectionHolder.lambda$connect$0(ConnectionHolder.java:58)
        at io.vertx.core.net.impl.NetClientImpl.lambda$connect$1(NetClientImpl.java:67)
        at io.vertx.core.net.impl.NetClientBase.lambda$connected$6(NetClientBase.java:242)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:335)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:193)
        at io.vertx.core.net.impl.NetClientBase.connected(NetClientBase.java:240)
        at io.vertx.core.net.impl.NetClientBase.lambda$doConnect$5(NetClientBase.java:212)
        at io.vertx.core.net.impl.ChannelProvider.lambda$connect$0(ChannelProvider.java:40)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
        at io.netty.util.concurrent.DefaultPromise.access$000(DefaultPromise.java:34)
        at io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:431)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vietj** [comment]
are you able to observe this consistently ?

**Comment by vietj** [comment]
what is your version ? 3.4.2 ?

**Comment by vietj** [comment]
@gjroylance ping ?

**Comment by vietj** [comment]
closing this issue until it we can get more info and a possible reproducer
