### ISSUE TITLE
Some of the requests are fail because of  java.lang.NullPointerException on vertx 3.5.0

### ISSUE THREAD

**Issue by michaelkub** [eclipse/vert.x#2196]
I got NullPointerException, during serving some of requests on vertx 3.5.0
The issue is not occurring on vertx 3.4.2 and 3.3.3.
I am using java 8 (exception occurred on Windows and Linux) 
Problem occurred with both ssl enabled and ssl disabled options
The full stack trace is:

```
java.lang.NullPointerException
	at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:444)
	at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:156)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:661)
	at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:614)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.vertx.core.http.impl.HttpServerImpl$Http2UpgradeHandler.channelRead(HttpServerImpl.java:929)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1336)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1127)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1162)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks in advance

**Comment by vietj** [comment]
can you tell how it happens ? it seems that the HttpServer requestHandler is null, can you check you don't see a null request handler ? are you using websockets ?

**Comment by michaelkub** [comment]
In  my scenario it is happens for  different requests, in most cases it is happens during access for static resources.
This is example of request:
DefaultHttpRequest(decodeResult: success, version: HTTP/1.1)
GET /login/vendor.js HTTP/1.1
Host: localhost:8443
Connection: keep-alive
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
Accept: */*
Referer: https://localhost:8443/login/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: cookie-session=8ae2590b5301d1e5af915a6f07750
Yep, I am using web socket
Also, I saw during debug that requestHandler is set to null,

**Comment by vietj** [comment]
can you provide a project reproducing the issue ?

**Comment by michaelkub** [comment]
Hi, I think I found a problem, it is look like my bug. In my project was created two instances of HttpServer one for routing and second one for webSocket only.
Idea was support a different ports for http calss and web socket. In case of the same port, second http server was created without requestHandler, so this was cause for null.
This is example of wrong code:
vertx.createHttpServer(options).requestHandler(router::accept).listen(getHttpPort(), ar -> {
            if(ar.succeeded()) {
                vertx.createHttpServer(options).websocketHandler(new WebSocketServerHandler()).listen(getWebSocketPort(), ra -> {
                    if(ra.succeeded()) {
                        startFuture.complete();
                    } else {
                        startFuture.fail("Fail to listen for websocets");
                    }
                });
            } else {
                startFuture.fail("Fail to listen on port " + getHttpPort());
            }
        });
 I am closing an issue, thank you for reply

**Comment by vietj** [comment]
thanks for reporting! I was also doubtfully about an `HttpServer` bug in your case

**Comment by b3lowster** [comment]
I've received the same exception but And I'm using websockets as well. But I couldn't reproduce it yet

**Comment by b3lowster** [comment]
I figured out that issue appeared when ws client working through proxy

**Comment by vietj** [comment]
can you elaborat how to reproduce it ? the NPE is not normal.

**Comment by luengnat** [comment]
`requestHandler` can be null at line 444?

**Comment by b3lowster** [comment]
I'll try to reproduce this issue tomorrow

**Comment by b3lowster** [comment]
Hi guys
First of all I'd like to share with you my environment and conditions:
I have an application (vert.x 3.5.0) with websocket server and mobile application which is using following java client https://github.com/TakahikoKawasaki/nv-websocket-client (I don't know what version is)

When mobile application works in ordinary way there are no any problems It can open ws connection but when I run turbo vpn on the mobile phone and try to open ws connection I receive an NullPointer exception

As far as I got the problem is here
**/io/vertx/core/http/impl/HttpServerImpl.java:633**
`if (request.headers().contains(io.vertx.core.http.HttpHeaders.UPGRADE, io.vertx.core.http.HttpHeaders.WEBSOCKET, true)) `

It seems that vpn affects to headers and instead of working on websockets request is working as an ordinary http request
```
//HTTP request
conn.handleMessage(msg);
```
Are there enough details?

**Comment by b3lowster** [comment]
my skype is vladimir.ts.il if someone needs more details please feel free to contact me

**Comment by b3lowster** [comment]
I have one more issue regarding sending message via websocket + rxSend

`vertx.eventBus().rxSend(clientSessionId, jsonMessage).subscribe();`

> Unhandled exception 
> rx.exceptions.OnErrorNotImplementedException: Timed out after waiting 30000(ms) for a reply. address: 1, repliedAddress: 88d066e4-7924-43e8-b915-6d9a52ca7aff
> 	at rx.functions.Actions$NotImplemented.call(Actions.java:576)
> 	at rx.functions.Actions$NotImplemented.call(Actions.java:572)
> 	at rx.Single$11.onError(Single.java:1794)
> 	at io.vertx.rx.java.SingleOnSubscribeAdapter.lambda$call$0(SingleOnSubscribeAdapter.java:33)
> 	at io.vertx.rxjava.core.eventbus.EventBus$1.handle(EventBus.java:113)
> 	at io.vertx.rxjava.core.eventbus.EventBus$1.handle(EventBus.java:108)
> 	at io.vertx.core.eventbus.impl.HandlerRegistration.sendAsyncResultFailure(HandlerRegistration.java:116)
> 	at io.vertx.core.eventbus.impl.HandlerRegistration.lambda$new$0(HandlerRegistration.java:67)
> 	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:870)
> 	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:829)
> 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: (TIMEOUT,-1) Timed out after waiting 30000(ms) for a reply. address: 1, repliedAddress: 88d066e4-7924-43e8-b915-6d9a52ca7aff
> 	... 10 more

**Comment by MazizEsa** [comment]
Might be a bug. Using 3.5.0. Create stomp webserver via websocket as in example http://vertx.io/docs/vertx-stomp/java/#_using_the_stomp_server_with_web_sockets. Try running it and the NPE will be displayed. Understandable since stomp server is not using requestHandler and is using websockethandler.
