### ISSUE TITLE
java.lang.IllegalArgumentException: \etc\resolv.conf didn't provide any name servers

### ISSUE THREAD

**Issue by shenzhenMirren** [eclipse/vert.x#2204]
when I use  version 3.5 vertx,it always appears 
java.lang.IllegalArgumentException: \etc\resolv.conf didn't provide any name servers,my system is Windows ,
so I want to ask reason,why?

`
2017-11-09 17:45:33 --> failed to parse /etc/resolv.conf and/or /etc/resolver
---------------------->  at io.netty.util.internal.logging.Slf4JLogger.debug(Slf4JLogger.java:86) 
 
java.lang.IllegalArgumentException: \etc\resolv.conf didn't provide any name servers
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:98)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:124)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.parseSilently(UnixResolverDnsServerAddressStreamProvider.java:66)
	at io.netty.resolver.dns.DnsServerAddressStreamProviders.<clinit>(DnsServerAddressStreamProviders.java:28)
	at io.netty.resolver.dns.DnsNameResolverBuilder.<init>(DnsNameResolverBuilder.java:54)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1$1.newNameResolver(DnsResolverProvider.java:137)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:86)
	at io.netty.resolver.dns.DnsAddressResolverGroup.newResolver(DnsAddressResolverGroup.java:73)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.resolver.DnsResolverProvider$1.newResolver(DnsResolverProvider.java:184)
	at io.netty.resolver.AddressResolverGroup.getResolver(AddressResolverGroup.java:69)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:83)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:766)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:87)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:344)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:226)
	at verticle.MainVerticle.start(MainVerticle.java:15)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:111)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$10(DeploymentManager.java:481)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Unknown Source)`

**Comment by shenzhenMirren** [comment]
system is win 10 1704

**Comment by vietj** [comment]
thanks for reporting, can you trace the code and understand why UnixResolverDnsServerAddressStreamProvider is used ?

**Comment by shenzhenMirren** [comment]
my system is Windows,but there is a error appear that is  \etc\resolv.conf didn't provide any name servers,
I don't think there is file like \etc\resolv.conf

`
2017-11-10 10:37:35 --> failed to parse /etc/resolv.conf and/or /etc/resolver
---------------------->  at io.netty.util.internal.logging.Slf4JLogger.debug(Slf4JLogger.java:86) 
java.lang.IllegalArgumentException: \etc\resolv.conf didn't provide any name servers
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:98)
	at io.netty.resolver.dns.UnixResolverDnsServerAddressStreamProvider.<init>(UnixResolverDnsServerAddressStreamProvider.java:124)`

**Comment by vietj** [comment]
I'm rather wondering why UnixResolverDnsServerAddressStreamProvider is used at all given that windows is not an unix system

**Comment by shenzhenMirren** [comment]
I have getted used to Windows development

**Comment by vietj** [comment]
I'm not saying that :-) , I'm just asking you, if by chance you could debug the source code on your machine to understand why UnixResolverDnsServerAddressStreamProvider is used in your particular case as it does not seem to happen on other windows.

**Comment by shenzhenMirren** [comment]
ok thank you

**Comment by dreamkidd** [comment]
@shenzhenMirren have u fixed this?
I have got the same problem on win10...
in `io.vertx.core.impl.resolver.DnsResolverProvider.java`:184 Line use the `DnsNameResolverBuilder()` but `DnsNameResolverBuilder` has a method whitch is called `platformDefault()`

this function is not supposed on windows

but i also wonder know to fix this... thanks a lot
@vietj

**Comment by normanmaurer** [comment]
@vietj @dreamkidd @shenzhenMirren this is a bug in netty: https://github.com/netty/netty/pull/7403

**Comment by dreamkidd** [comment]
@shenzhenMirren @normanmaurer @vietj 
yes,i have figure it out , This does not affect your vertx program.
if you won't to see this log just Increase the log level.
This problem will only appear on the windows.
hope netty could repair this probablem as soon as possible

**Comment by vietj** [comment]
thanks @normanmaurer  for the heads-up

**Comment by shenzhenMirren** [comment]
I'm using version 3.4.2 now, but to solve this problem, you can use 
`System.setProperty ("vertx.disableDnsResolver", "true");`

If fat-jar is started, `Java -jar xxx.jar -Dvertx.disableDnsResolver=true` can be used
