### ISSUE TITLE
The WebSocket should check there is a handler for pong before delivering the pong event

### ISSUE THREAD

**Issue by mvdavid7** [eclipse/vert.x#2255]
We recently upgraded to vertx 3.5 and are seeing this exception in our logs
Stack Trace:
```
java.lang.NullPointerException: null
    at io.vertx.core.http.impl.WebSocketImplBase.handleFrame(WebSocketImplBase.java:266)
    at io.vertx.core.http.impl.ServerConnection.handleWsFrame(ServerConnection.java:336)
    at io.vertx.core.http.impl.ServerConnection.processMessage(ServerConnection.java:452)
    at io.vertx.core.http.impl.ServerConnection.handleMessage(ServerConnection.java:156)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:671)
    at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:614)
    at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:150)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:342)
    at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:200)
    at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:148)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Thread.java:745)
```

We don't have (or need) a pong handler attached to the `ServerWebSocket` instance but have clients that will send pong frames to our websocket servers, so we see this exception being logged.

**Comment by vietj** [comment]
can you try with 3.5.1-SNAPSHOT ?

now the code checks the frame handler is not null

**Comment by vietj** [comment]
can you check the stack trace ?

at line 266 in 3.5.0 I can see : 

```
          if (frameHandler != null) {
```

wich cannot produce an NPE

**Comment by vietj** [comment]
actually sorry I had a wrong tag locally :-)

**Comment by vietj** [comment]
so yes it's still here

**Comment by vietj** [comment]
question : why your clients are sending unsollicited pong frames ?

**Comment by vietj** [comment]
fixed - no test, there is no real way to test this

**Comment by mvdavid7** [comment]
The websocket implementation libraries for some of our clients are out of our control and happen to send PONG frames unsolicited.

**Comment by mvdavid7** [comment]
Do you have a timeframe for the 3.5.1 release?

**Comment by vietj** [comment]
@mvdavid7 in the coming weeks, we are in the preparation phase right now
