### ISSUE TITLE
3.5.0: WebSocket is closed exception when socket closed under load

### ISSUE THREAD

**Issue by sfitts** [eclipse/vert.x#2281]
Version: 3.5.0

We are using the SockJS support and specifically the part that allows you to send data to an open websocket via an event bus address.  When there is a socket which is under heavy load (lots of data being written over the bus) and that socket is closed, we sometimes see the following exceptions:

```
23:44:59.237 [vert.x-eventloop-thread-2] ERROR i.v.c.e.impl.HandlerRegistration - Failed to handleMessage. address: 43552bcc-57e8-42fc-91c6-26d5028aaa25
java.lang.IllegalStateException: WebSocket is closed
        at io.vertx.core.http.impl.WebSocketImplBase.checkClosed(WebSocketImplBase.java:253)
        at io.vertx.core.http.impl.WebSocketImplBase.writeBinaryMessage(WebSocketImplBase.java:156)
        at io.vertx.core.http.impl.ServerWebSocketImpl.writeBinaryMessage(ServerWebSocketImpl.java:43)
        at io.vertx.ext.web.handler.sockjs.impl.RawWebSocketTransport$RawWSSockJSSocket.write(RawWebSocketTransport.java:86)
        at io.vertx.ext.web.handler.sockjs.impl.SockJSSocketBase.lambda$new$0(SockJSSocketBase.java:70)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:189)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:538)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
23:44:59.237 [vert.x-eventloop-thread-2] ERROR io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.IllegalStateException: WebSocket is closed
        at io.vertx.core.http.impl.WebSocketImplBase.checkClosed(WebSocketImplBase.java:253)
        at io.vertx.core.http.impl.WebSocketImplBase.writeBinaryMessage(WebSocketImplBase.java:156)
        at io.vertx.core.http.impl.ServerWebSocketImpl.writeBinaryMessage(ServerWebSocketImpl.java:43)
        at io.vertx.ext.web.handler.sockjs.impl.RawWebSocketTransport$RawWSSockJSSocket.write(RawWebSocketTransport.java:86)
        at io.vertx.ext.web.handler.sockjs.impl.SockJSSocketBase.lambda$new$0(SockJSSocketBase.java:70)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:189)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:538)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:745)
```

These are benign and we think due to the timing of processing in-flight events and the closing of the socket (that close does unregister the event bus consumer, but obviously not in a way that guarantees that no further messages will be processed by the handler).

Unfortunately for our deployed server this results in a near constant spam of these error messages (it doesn't happen all the time, but often enough that at scale we are getting at least one every few seconds).  We'd rather not turn the logger off entirely since sometimes errors like this indicate an actual problem.

Possible solutions:

* Wrap the write to the socket at line 70 in SockJSSocketBase.java with a try/catch to consume the exception in this case.
* Provide a way for us to replace the write handler used by the Socks code with our own so we can catch/consume the exception.
* Guarantee that no data will be delivered to the handler after a close has occurred (not sure if that's possible/a good idea).

**Comment by sfitts** [comment]
Sorry, just realized this belongs in web, not core.  I'll re-open there
