### ISSUE TITLE
ServerHandler throws NPE when shutdown is in progress

### ISSUE THREAD

**Issue by ctron** [eclipse/vert.x#2291]
While HTTP requests are fired against a vertx based HTTP server and a shutdown is initiated the following exceptions start appearing in the logs:

~~~
14:10:05.743 [vert.x-eventloop-thread-0] WARN  i.n.c.AbstractChannelHandlerContext - An exception '{}' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.channel.ChannelPipelineException: io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:626)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:201)
	at io.vertx.core.http.impl.HttpServerImpl.configureHttp1(HttpServerImpl.java:461)
	at io.vertx.core.http.impl.HttpServerImpl.access$700(HttpServerImpl.java:109)
	at io.vertx.core.http.impl.HttpServerImpl$1$1.configure(HttpServerImpl.java:319)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:48)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:27)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: null
	at io.vertx.core.http.impl.ServerHandler.handlerAdded(ServerHandler.java:47)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
	... 21 common frames omitted
~~~

**Comment by vietj** [comment]
For the record, here is a reproducer : 

```
public class Main {

  static Vertx vertx = Vertx.vertx();

  static Supplier<Verticle> verticle = () -> new AbstractVerticle() {
    @Override
    public void start(Future<Void> startFuture) {
      vertx.createHttpServer().requestHandler(req -> req.response().end("Hello")).listen(8080, "localhost", ar -> {
        if (ar.succeeded()) {
          startFuture.complete();
        } else {
          startFuture.fail(ar.cause());
        }
      });
    }
  };

  public static void main(String[] args) {
    vertx.deployVerticle(verticle, new DeploymentOptions().setInstances(1), ar -> {
      System.out.println("started base server " + ar.succeeded());
    });
    startStopServers();
  }

  private static void startStopServers() {
    vertx.deployVerticle(verticle, new DeploymentOptions().setInstances(4), ar1 -> {
      if (ar1.succeeded()) {
        vertx.setTimer(100, id -> {
          vertx.undeploy(ar1.result(), ar2 -> {
            startStopServers();
          });
        });
      } else {
        System.out.println("Could not deploy verticle");
        ar1.cause().printStackTrace();
      }
    });
  }
}
```

run along with :

```
> wrk --header "Connection: Close" -d 100 -c 256 http://localhost:8080
```

**Comment by vietj** [comment]
still happens with 3.5.1-SNAPSHOT:

```
WARNING: An exception 'java.lang.NullPointerException' [enable DEBUG level for full stacktrace] was thrown by a user handler's exceptionCaught() method while handling the following exception:
io.netty.channel.ChannelPipelineException: io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handlerAdded() has thrown an exception; removed.
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:626)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:235)
	at io.netty.channel.DefaultChannelPipeline.addLast(DefaultChannelPipeline.java:201)
	at io.vertx.core.http.impl.HttpServerImpl.configureHttp1(HttpServerImpl.java:467)
	at io.vertx.core.http.impl.HttpServerImpl.access$700(HttpServerImpl.java:104)
	at io.vertx.core.http.impl.HttpServerImpl$1$1.configure(HttpServerImpl.java:314)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:59)
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at io.vertx.core.http.impl.Http1xServerHandler.handlerAdded(Http1xServerHandler.java:58)
	at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:606)
```
