### ISSUE TITLE
Unable to read SSL certificates from jar

### ISSUE THREAD

**Issue by bmwcmw** [eclipse/vert.x#2340]
Hi, 

Sometimes we want to use key files provided by jar balls, but vertx cannot handle the path.

It'll be cool if vertx allows to look for resources by relative paths in classloader (and use them for SSL certificates in this case).

More information :
### Version

* vert.x core: 3.5.1
* vert.x web: 3.5.1
* openjdk version "1.8.0_151" with 64-Bit Server VM (build 25.151-b12, mixed mode)

### Steps to reproduce

1. Package key files *.pem in jar : 
- ssl/privKey.pem
- ssl/cert_fullchain.pem
- ssl/AddTrustExternalCARoot.pem

2. Add them to options
```        
        PemKeyCertOptions pemKeyCertOptions = new PemKeyCertOptions()
            .addKeyPath(ClassLoader.getSystemResource("ssl/privKey.pem").toExternalForm())
            .addCertPath(ClassLoader.getSystemResource("ssl/cert_fullchain.pem").toExternalForm());
        PemTrustOptions pemTrustOptions = new PemTrustOptions()
            .addCertPath(ClassLoader.getSystemResource("ssl/AddTrustExternalCARoot.pem").toExternalForm());

        HttpServerOptions httpsOptions =
                new HttpServerOptions()
                        ...
                        .setSsl(true)
                        .setKeyCertOptions(pemKeyCertOptions)
                        .setTrustOptions(pemTrustOptions)
                        ...

```
3. Create a server and listen to HTTPS port
```
HttpServer server = vertx.createHttpServer(httpsOptions);
server.listen(443);
```

### Extra
* ClassLoader.getSystemResource("ssl/*.pem").getPath() doesn't work either

The problem begins from io.vertx.core.file.impl.FileSystemImpl#readFileInternal line 736 byte[] `bytes = Files.readAllBytes(target);` it seems this one cannot handle zip file systems

`ClassLoader.getResourceAsStream(...)` works for this special case

* Error message
```
io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /home/bmwcmw/dev/projects/application/jar:file:/home/bmwcmw/dev/projects/application/build/libs/fatJar.jar!/ssl/ssl_trust_file.pem
io.vertx.core.VertxException: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /home/bmwcmw/dev/projects/application/jar:file:/home/bmwcmw/dev/projects/application/build/libs/fatJar.jar!/ssl/AddTrustExternalCARoot.crt
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:455)
	at io.vertx.core.net.impl.SSLHelper.validate(SSLHelper.java:482)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:254)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:222)
	at com.demo.WebServer.start(WebServer.java:230)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.vertx.core.file.FileSystemException: java.nio.file.NoSuchFileException: /home/bmwcmw/dev/projects/application/jar:file:/home/bmwcmw/dev/projects/application/build/libs/fatJar.jar!/ssl/AddTrustExternalCARoot.crt
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:740)
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:732)
	at io.vertx.core.file.impl.FileSystemImpl.readFileBlocking(FileSystemImpl.java:296)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1357)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
	at io.vertx.core.net.impl.KeyStoreHelper.loadCA(KeyStoreHelper.java:330)
	at io.vertx.core.net.impl.KeyStoreHelper.create(KeyStoreHelper.java:124)
	at io.vertx.core.net.TrustOptions.getTrustManagerFactory(TrustOptions.java:43)
	at io.vertx.core.net.impl.SSLHelper.getTrustMgrFactory(SSLHelper.java:322)
	at io.vertx.core.net.impl.SSLHelper.getContext(SSLHelper.java:453)
	... 14 common frames omitted
...
Caused by: java.nio.file.NoSuchFileException: /home/bmwcmw/dev/projects/application/jar:file:/home/bmwcmw/dev/projects/application/build/libs/fatJar.jar!/ssl/AddTrustExternalCARoot.crt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.Files.readAllBytes(Files.java:3152)
	at io.vertx.core.file.impl.FileSystemImpl$13.perform(FileSystemImpl.java:736)
	... 30 common frames omitted
```

Thanks.

**Comment by vietj** [comment]
have you tried using directly "ssl/cert_fullchain.pem" ? it should load from the jar.

**Comment by bmwcmw** [comment]
I works like a charm. Thanks Julien.
