### ISSUE TITLE
Uncaught exception in Netty pipeline

### ISSUE THREAD

**Issue by vmaurin** [eclipse/vert.x#2374]
Hello,
While running servers with vert.x 3.5.1 (vertx + vertx web), I got
"An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception."
The exception itself is an java.lang.IllegalArgumentException thrown by io.netty.handler.codec.http.HttpVersion either for empty version or invalid version.
So far I was not able torreproduce this error with a simple example, but here some observations : 
If I send a valid HTTP request (with keep alive) and then an invalid HTTP request (like GET / HTTP/dummy), I got the IllegalArgumentException, but it is actually catched and logged by vertx ConnectionBase.
In the case where I got  "An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.", it is actually not caught by vert.x at all, and it is looping forever (like the error is not "consumed" from the event loop).

Here the stack trace
```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.lang.IllegalArgumentException: invalid version format: (LINUX; U; ANDROID 4.3; RU-RU; GT-I9300I BUILD/JLS36C) APPLEWEBKIT/534.30 (KHTML, LIKE GECKO) VERSION/4.0 MOBILE SAFARI/534.30 
 at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121)
 at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76)
 at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87)
 at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219)
 at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
 at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
 at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
 at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
 at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
 at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
 at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(Thread.java:745)
```

**Comment by vietj** [comment]
Hi,

if that's the first request the connection has not yet been recognized as an HTTP/1 request and thus the error will be handled by the HttpServer#exceptionHandler (it may be also an HTTP/2 connection)

when it's the second request, the HttpConnection object has been created and the HttpConnection#exceptionHandler should propagate it

the error you are observing means that the handler was not yet there, so it might be before the server has decided it's an HTTP/1 versus HTTP/2 or during a protocol upgrade that removes the handler (and thus it would be a bug)

**Comment by vietj** [comment]
if you can provide a reproducer or context about it, it would be great!

**Comment by vmaurin** [comment]
@vietj  Thank you for the fast reply.
Unfortunately, I was not able to reproduce it so far (it is appearing randomly on servers receiving 1B requests/day and loop/log infinitely on the error).
According what you say, I will try to go in this direction.
Note that I have done some test with vert.x 3.3.3 and here I got the exception catched by the ConnectionBase, whatever is the first or second request that is invalid

**Comment by vmaurin** [comment]
Ok with your advice, I reproduce the error

Here the server code
```java
import io.vertx.core.Vertx;
import io.vertx.core.VertxOptions;

public class Main {

    public static void main(String[] args) {

        Vertx vertx = Vertx.vertx(new VertxOptions().setEventLoopPoolSize(1));

        vertx.createHttpServer()
             .requestHandler(request -> request.response().end())
             .listen(8080);

        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            vertx.close();
        }, "shutdown-thead"));
    }
}
```

Then with netcat, I send the following requests in a single connection
```
GET / HTTP/1.1
Connection: Upgrade
Upgrade: HTTP/2.0

GET / invalid

```

It is resulting netty looping with the following error
```
An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
 java.lang.IllegalArgumentException: invalid version format: INVALID
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:121) ~[netty-codec-http-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:76) ~[netty-codec-http-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.http.HttpRequestDecoder.createMessage(HttpRequestDecoder.java:87) ~[netty-codec-http-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:219) ~[netty-codec-http-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.end(Http1xOrH2CHandler.java:60) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.vertx.core.http.impl.Http1xOrH2CHandler.channelRead(Http1xOrH2CHandler.java:38) ~[vertx-core-3.5.1.jar:3.5.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.19.Final.jar:4.1.19.Final]
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
can you check with vertx master ? I've done changes there recently

**Comment by vmaurin** [comment]
Ok I will try. Narrowing down the issue, it is actually when there are unexpected additional bytes in a keep-alive query.
An other example
```
POST / HTTP/1.1
Host: localhost:8080
Content-Length: 4
Content-Type: text/plain

too-long
```

**Comment by vietj** [comment]
if you can provide reproducers for all case that's great :-)

**Comment by vietj** [comment]
there are already tests similar for that in Http1xTest, for instance for checking invalid chunked encoding

**Comment by vmaurin** [comment]
So with master branch and the server code above, the behavior is having the IllegalArgumentException in the server exceptionHandler, I guess that makes sense (the first request is processed, then the leading bytes are considered as invalid second http request).

Regarding tests, I am not able to write one, I don't understand why.
I have tried
```java
  @Test
  public void testTooLongContentInHttpServerRequest() throws Exception {
    server.requestHandler(req -> {
      req.response().end();
    });
    server.exceptionHandler(error -> {
      assertEquals(IllegalArgumentException.class, error);
      testComplete();
    });
    startServer();
    NetClient client = vertx.createNetClient();
    client.connect(DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, onSuccess(so -> {
      so.write("POST / HTTP/1.1\r\n");
      so.write("Content-Length: 4\r\n");
      so.write("\r\n");
      so.write("toolong\r\n");
    }));
    await();
  }
```

But then the exception in unhandled.

**Comment by vietj** [comment]
I will have a look quickly with your test and report

**Comment by vietj** [comment]
the code needs to be 

```
      assertEquals(IllegalArgumentException.class, error.getClass());
```

**Comment by vietj** [comment]
this passes constantly:

```
  @Test
  public void testTooLongContentInHttpServerRequest() throws Exception {
    server.requestHandler(req -> {
      req.response().end();
    });
    server.connectionHandler(conn -> {
      conn.exceptionHandler(error -> {
        assertEquals(IllegalArgumentException.class, error.getClass());
        testComplete();
      });
    });
    server.exceptionHandler(error -> {
      assertEquals(IllegalArgumentException.class, error.getClass());
      testComplete();
    });
    startServer();
    NetClient client = vertx.createNetClient();
    try {
      client.connect(DEFAULT_HTTP_PORT, DEFAULT_HTTP_HOST, onSuccess(so -> {
        so.write("POST / HTTP/1.1\r\n");
        so.write("Content-Length: 4\r\n");
        so.write("\r\n");
        so.write("toolong\r\n");
      }));
      await();
    } finally {
      client.close();
    }
  }
```

what is weird is the exception handler on connection or server is chosen randomly and I haven't figured out yet why

**Comment by vietj** [comment]
so if I replace in `Http1xOrH2CHandler`:

```
ctx.fireChannelRead(buf);
ctx.pipeline().remove(this);
```

by

```
ctx.pipeline().remove(this);
ctx.fireChannelRead(buf);
```

it fails consistently on the connection exception handler, so I think that the pipeline update creates a (safe) race

**Comment by vietj** [comment]
if I print the actual buffers received here is what we get

```
*** Iteration 183/1000 of test
Connection
BUF POST / HTTP/1.1
Content-Length: 4

toolong

2
Starting test: Http1xTest#testTooLongContentInHttpServerRequest 
*** Iteration 184/1000 of test
Connection
BUF POST / HTTP/1.1
Content-Length: 4

1
```

1: means fail in one handler
2: means fail in another

so it makes sense to me now

**Comment by vietj** [comment]
so I will change to

```
ctx.pipeline().remove(this);
ctx.fireChannelRead(buf);
```

because the failure should happen at the connection level and not at the server level since HTTP/1 was identified as protocol

**Comment by vmaurin** [comment]
When I send directly an invalid protocol (so connecting and send `GET / invalid` for example), I get a server error. That could means that sometime we will get the IllegalArgumentException in server handler or in connection handler depending if one request has been processed or not. Somehow it could make sense, but it could lead to some confusion ? Could it be better to group all protocol parsing exception in the same place ?

**Comment by vietj** [comment]
with the patch I'm doing, it should always be processed consistently in the HttpConnection handler

**Comment by vietj** [comment]
there is alraedy a similar test that tests invalid HTTP value : look at Http1xTest#testIncorrectHttpVersion

**Comment by vietj** [comment]
@vmaurin please see https://github.com/eclipse/vert.x/tree/http1xorh2chandler-removes-itself-before

**Comment by vmaurin** [comment]
@vietj It is looking good to me. Maybe the invalid request test here https://github.com/eclipse/vert.x/compare/master...http1xorh2chandler-removes-itself-before#diff-73e097b00cba4c4e2fe7cc0d5ebccf69R1691 should actually be looking more like a request no ?

**Comment by vietj** [comment]
what do you mean ?

**Comment by vmaurin** [comment]
The request string is `HTTP/1.2 200 OK\r\nContent-Length:5\r\n\r\nHELLO`
Should it be better with `POST / HTTP/1.2\r\nContent-Length:5\r\n\r\nHELLO` ?

**Comment by vietj** [comment]
we can but from the internal behavior perspective it is not necessary as the http server decode does not make HTTP interpretation

**Comment by vietj** [comment]
ah yes it should, sorry

**Comment by javad-salehi** [comment]
vertx 3.8.4 has the same problem, but only in http/1.x secure

**Comment by vietj** [comment]
@javad-salehi can you provide a reproducer ?
