### ISSUE TITLE
Http1xServerConnection's processMessage seems to hang one of my event-loops

### ISSUE THREAD

**Issue by yacota** [eclipse/vert.x#2388]
Our server is using Vertx 3.5.1, it handles thousands of request/sec from thousands of JS clients. Those JS clients sometimes create rubbish request with strange chars

    ar.bids%±FÌo¥out=false&

When processing query parameters with invalid chars like the one above we don't have problems because Http1xServerConnection's processMessage always return true, this can be check with the following stack trace

    java.lang.IllegalArgumentException: unterminated escape sequence at index 510 of: /someurl?ar.bids%5B2%5D.tout=false
        at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:349)
        at io.netty.handler.codec.http.QueryStringDecoder.addParam(QueryStringDecoder.java:257)
        at io.netty.handler.codec.http.QueryStringDecoder.decodeParams(QueryStringDecoder.java:245)
        at io.netty.handler.codec.http.QueryStringDecoder.parameters(QueryStringDecoder.java:180)
        at io.vertx.ext.web.impl.RouteImpl.matches(RouteImpl.java:298)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:110)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:120)
        at io.vertx.ext.web.impl.RouterImpl.accept(RouterImpl.java:79)
        at io.vertx.core.http.impl.Http1xServerConnection.processMessage(Http1xServerConnection.java:433)
        at io.vertx.core.http.impl.Http1xServerConnection.handleMessage(Http1xServerConnection.java:141)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:683)
        at io.vertx.core.http.impl.HttpServerImpl$ServerHandlerWithWebSockets.handleMessage(HttpServerImpl.java:636)
        at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
        at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

But when **request.decoderResult().isFailure()** returns true (from Http1xServerConnection's processMessage) and after invoking handleError method, the request is queued again (Http1xServerConnection's  handleMessage), so event loop will handle it again later

Actually I am "quite sure" about this because now this machine does not receive any request, it has been disconnected from the load balancer, and this event-loop is still using lots of resources 

I attach some stack traces of the problematic event-loop

Stack Trace

```
ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus line: 373 
   ch.qos.logback.classic.Logger.warn line: 692 
   io.netty.util.internal.logging.Slf4JLogger.warn line: 151 
   io.netty.channel.DefaultChannelPipeline.onUnhandledInboundException line: 1158 
   io.netty.channel.DefaultChannelPipeline$TailContext.exceptionCaught line: 1241 
   io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught line: 285 
   io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught line: 264 
   io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught line: 256 
   io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught line: 1326 
   io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught line: 285 
   io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught line: 264 
   io.netty.channel.DefaultChannelPipeline.fireExceptionCaught line: 923 
   io.vertx.core.http.impl.Http1xServerConnection.handleError line: 409 
   io.vertx.core.http.impl.Http1xServerConnection.processMessage line: 420 
   io.vertx.core.http.impl.Http1xServerConnection.lambda$checkNextTick$3 line: 489 
   io.vertx.core.http.impl.Http1xServerConnection$$Lambda$81/1471778344.handle line: not available 
   io.vertx.core.impl.ContextImpl.lambda$wrapTask$2 line: 339 
   io.vertx.core.impl.ContextImpl$$Lambda$33/1449263511.run line: not available 
   io.netty.util.concurrent.AbstractEventExecutor.safeExecute line: 163 
   io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks line: 404 
   io.netty.channel.nio.NioEventLoop.run line: 463 
   io.netty.util.concurrent.SingleThreadEventExecutor$5.run line: 886 
   io.netty.util.concurrent.FastThreadLocalRunnable.run line: 30 
   java.lang.Thread.run line: 748 
```

Stack trace

   ```
 io.vertx.core.impl.EventLoopContext.executeAsync line: 39 
   io.vertx.core.impl.ContextImpl.runOnContext line: 204 
   io.vertx.core.impl.VertxImpl.runOnContext line: 337 
   io.vertx.core.http.impl.Http1xServerConnection.checkNextTick line: 483 
   io.vertx.core.http.impl.Http1xServerConnection.lambda$checkNextTick$3 line: 504 
   io.vertx.core.http.impl.Http1xServerConnection$$Lambda$81/1471778344.handle line: not available 
   io.vertx.core.impl.ContextImpl.lambda$wrapTask$2 line: 339 
   io.vertx.core.impl.ContextImpl$$Lambda$33/1449263511.run line: not available 
   io.netty.util.concurrent.AbstractEventExecutor.safeExecute line: 163 
   io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks line: 404 
   io.netty.channel.nio.NioEventLoop.run line: 463 
   io.netty.util.concurrent.SingleThreadEventExecutor$5.run line: 886 
   io.netty.util.concurrent.FastThreadLocalRunnable.run line: 30 
   java.lang.Thread.run line: 748 
```

**Comment by tsegismont** [comment]
Can you try with a 3.6 snapshot build? I believe this has been fixed in
master.

2018-04-14 0:31 GMT+02:00 Jordi Llach <notifications@github.com>:

**Comment by vietj** [comment]
@yacota as @tsegismont said you should check with master, we intent to backport these fixes in a 3.52

**Comment by vietj** [comment]
any news about it ?

**Comment by jordillachmrf** [comment]
Tomorrow we will shuttle a new version with Vertx 3.6.0-SNAPSHOT

**Comment by jordillachmrf** [comment]
So far so good, but the problem did not happen on a daily basis ... we used to have problems every 2,3 days

**Comment by yacota** [comment]
We haven't had any other issue, feel free to close this issue. Thanks

**Comment by vietj** [comment]
thanks for checking!
