### ISSUE TITLE
Netty upgrade to 4.1.22.Final

### ISSUE THREAD

**Issue by johnfg10** [eclipse/vert.x#2390]
Hello, 
Im using JDK 10 and have encountered an issue with the version of netty being used(https://github.com/netty/netty/issues/7768, where the owner said on the 4th of may, "Upgrade to latest Netty version as it was fixed there")

Language: Kotlin
JDK: 10
OS: Windows 10
IDE: Intellij Idea ultimate

Stack trace
```
13:15:33.467 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
13:15:33.467 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
13:15:33.468 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @59d016c9
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:360)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:589)
	at java.base/java.lang.reflect.Method.invoke(Method.java:556)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:312)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:303)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:208)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:79)
	at io.netty.util.ConstantPool.<init>(ConstantPool.java:32)
	at io.netty.util.Signal$1.<init>(Signal.java:27)
	at io.netty.util.Signal.<clinit>(Signal.java:27)
	at io.netty.util.concurrent.DefaultPromise.<clinit>(DefaultPromise.java:43)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:125)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:166)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:145)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:141)
	at io.vertx.core.impl.VertxFactoryImpl.vertx(VertxFactoryImpl.java:30)
	at io.vertx.core.Vertx.vertx(Vertx.java:78)
	at io.github.johnfg10.MainKt.main(Main.kt:8)
```

**Comment by vietj** [comment]
in which version is it fixed ?

**Comment by vietj** [comment]
we're planning to upgrade to 4.1.22.Final

**Comment by vietj** [comment]
in 3.6.0

**Comment by johnfg10** [comment]
I'm presuming he either means 4.1.22 or 4.1.23, is there a release date/prerelease for 3.6.0 yet?

**Comment by vietj** [comment]
@johnfg10 no there is no such date yet, we're currently looking at a 3.5.2 release

for the upgrade we have constraints due to gRPC that uses gRPC netty and has its own version of Netty
