### ISSUE TITLE
Showstopper: NoSuchMethodError during bootstrap

### ISSUE THREAD

**Issue by leolux** [eclipse/vert.x#2424]
When calling either "vertx.clusteredVertx(...);" or "vertx.Vertx.vertx();" the following exception gets thrown in 3.5.1:
```
Exception in thread "main" java.lang.NoSuchMethodError: io.netty.util.internal.ReflectionUtil.trySetAccessible(Ljava/lang/reflect/AccessibleObject;Z)Ljava/lang/Throwable;
	at io.netty.channel.nio.NioEventLoop$5.run(NioEventLoop.java:217)
	at java.security.AccessController.doPrivileged(Native Method)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:210)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at io.vertx.core.net.impl.transport.Transport.eventLoopGroup(Transport.java:125)
	at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:166)
	at io.vertx.core.impl.VertxFactoryImpl.clusteredVertx(VertxFactoryImpl.java:45)
	at io.vertx.core.Vertx.clusteredVertx(Vertx.java:100)
```

**Comment by leolux** [comment]
I have found the cause for this issue: I happens when adding the dependency to firebase-admin. It seems to be coming from a conflict between netty-common:4.1.19.FINAL and grpc-netty-shaded:1.10.1

Both versions of io.netty.util.internal.ReflectionUtil have the method trySetAccessible(Ljava/lang/reflect/AccessibleObject;Z). How to solve maven conflicts with firebase?

**Comment by dimitrijepetrovic** [comment]
This case was closed. Can you add how you fixed this please?

**Comment by vietj** [comment]
this was a wrong version dependency on netty brought by "firebase-admin"
