### ISSUE TITLE
ClusteredEventBus racy initialization

### ISSUE THREAD

**Issue by sonofingo** [eclipse/vert.x#2438]
Hi,

It seems as if there is a case in the ClusteredEventBus (3.5.1) where a NPE can appear. After trying out some different cluster manager implementations the following NPE appear from time to time on a new instance when it is being launched. This is the NPE that appears:
```
2018-05-11 16:14:32:531 +0200 [vert.x-eventloop-thread-1] ERROR ContextImpl - Unhandled exception
java.lang.NullPointerException
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$setClusterViewChangedHandler$9(ClusteredEventBus.java:283)
	at io.vertx.core.impl.HAManager.lambda$checkSubs$10(HAManager.java:516)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$11(HAManager.java:525)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

Looking at the code for the ClusteredEventBus it seems as if the member "subs" can be null when the view changed handler is called before the ClusteredEventBus has started completely. The view changed handler is set in the constructor but the "subs" member is only given a value in the method "start(...)". I briefly looked at previous versions of the ClusteredEventBus and there has previously been a null-check in the view changed handler.

Regards

**Comment by vietj** [comment]
it would be interesting to reproduce it with the fake manager in tests

**Comment by vietj** [comment]
by introducing a pause between the clustered event bus creation and its initialisation I can definitely reproduce it.

**Comment by vietj** [comment]
changing this method in VertxImpl:

```
  private void createAndStartEventBus(VertxOptions options, Handler<AsyncResult<Vertx>> resultHandler) {
    if (options.isClustered()) {
      eventBus = new ClusteredEventBus(this, options, clusterManager, haManager);
    } else {
      eventBus = new EventBusImpl(this);
    }
    try {
      Thread.sleep(20);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    eventBus.start(ar -> {
      if (ar.succeeded()) {
        if (resultHandler != null) resultHandler.handle(Future.succeededFuture(this));
      } else {
        log.error("Failed to start event bus", ar.cause());
        if (resultHandler != null) resultHandler.handle(Future.failedFuture(ar.cause()));
      }
    });
  }
```

and repeating a test that simply start nodes many times, it happens:

```
Unhandled exception 
java.lang.NullPointerException
	at io.vertx.core.eventbus.impl.clustered.ClusteredEventBus.lambda$setClusterViewChangedHandler$9(ClusteredEventBus.java:283)
	at io.vertx.core.impl.HAManager.lambda$checkSubs$10(HAManager.java:516)
	at io.vertx.core.impl.HAManager.lambda$runOnContextAndWait$11(HAManager.java:525)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:333)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:39)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
there is a PR for this issue @sonofingo https://github.com/eclipse/vert.x/pull/2440
