### ISSUE TITLE
Incorrect VertxHttp2Stream checkNextTick implementation

### ISSUE THREAD

**Issue by BillyYccc** [eclipse/vert.x#2457]
I'm building a HTTP2 proxy with Vert.x 3.5.1, when I try to migrate to 3.5.2.CR1, NullPointerException may happen when requests come
```
May 16, 2018 2:40:21 PM io.vertx.core.impl.ContextImpl
 SEVERE: Unhandled exception
 java.lang.NullPointerException
 	at io.vertx.core.http.impl.VertxHttp2Stream.checkNextTick(VertxHttp2Stream.java:104)
 	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 	at java.lang.Thread.run(Thread.java:748)

```

I guess this might be caused when `pending` deque is empty, see https://github.com/eclipse/vert.x/blob/47d15d66dcd56381ee07754545258d3c48537784/src/main/java/io/vertx/core/http/impl/VertxHttp2Stream.java#L103

**Comment by vietj** [comment]
thanks, do you know why it happens ?

**Comment by BillyYccc** [comment]
Here is a small reproducer https://gist.github.com/BillyYccc/6891cb36a4ddae0251a2a28aa99dfbbc.

In my use case I think this might be related to the vertx-web-client, a `HttpClientResponse#pause()` before any read happens may cause the empty pending deque to poll a **null** Buffer.

**Comment by vietj** [comment]
thanks @BillyYccc
