### ISSUE TITLE
vert.x 3.5.1 co.paralleluniverse.fibers.instrument.UnableToInstrumentException

### ISSUE THREAD

**Issue by mscofy** [eclipse/vert.x#2474]
I update vert.x from version 3.5.0 to 3.5.1,project run with errors,  this is my shell

java -javaagent:/Users/xxx/.m2/repository/co/paralleluniverse/quasar-core/0.7.9/quasar-core-0.7.9.jar=b -Dvertx.zookeeper.config=./zookeeper.json -jar target/aaa-fat.jar   -conf application-conf.json -cluster

[quasar] ERROR: Unable to instrument class io/vertx/core/impl/DeploymentManager$DeploymentImpl
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument io/vertx/core/impl/DeploymentManager$DeploymentImpl#lambda$rollback$1(Ljava/lang/Throwable;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/Handler;Lio/vertx/core/impl/ContextImpl;Lio/vertx/core/AsyncResult;)V because of synchronization
	at co.paralleluniverse.fibers.instrument.InstrumentMethod.dumpCodeBlock(InstrumentMethod.java:720)
	at co.paralleluniverse.fibers.instrument.InstrumentMethod.accept(InstrumentMethod.java:415)
	at co.paralleluniverse.fibers.instrument.InstrumentClass.visitEnd(InstrumentClass.java:265)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.asm.ClassReader.accept(Unknown Source)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:120)
	at co.paralleluniverse.fibers.instrument.QuasarInstrumentor.instrumentClass(QuasarInstrumentor.java:88)
	at co.paralleluniverse.fibers.instrument.JavaAgent$Transformer.transform(JavaAgent.java:187)
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.DeploymentManager.doDeploy(DeploymentManager.java:465)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeployVerticle$2(DeploymentManager.java:203)
	at io.vertx.core.impl.DeploymentManager$$Lambda$45/1076984738.handle(Unknown Source)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:76)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:171)
	at io.vertx.core.impl.DeploymentManager.doDeployVerticle(DeploymentManager.java:143)
	at io.vertx.core.impl.DeploymentManager.deployVerticle(DeploymentManager.java:131)
	at io.vertx.core.impl.VertxImpl.deployVerticle(VertxImpl.java:665)
	at io.vertx.core.Starter.runVerticle(Starter.java:328)
	at io.vertx.core.Starter.run(Starter.java:138)
	at io.vertx.core.Starter.main(Starter.java:96)

**Comment by vietj** [comment]
can you move this issue to https://github.com/vert-x3/vertx-sync/ ?
