### ISSUE TITLE
Java 10 issue: java.lang.IncompatibleClassChangeError: Method io.vertx.core.Future.succeededFuture()Lio/vertx/core/Future; must be InterfaceMethodref constant 

### ISSUE THREAD

**Issue by cinterloper** [eclipse/vert.x#2495]
FWIW im using some compiled groovy inside a java project, but not vertx-lang-groovy
$ java --version
openjdk 10.0.1 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 10.0.1+10-Ubuntu-3ubuntu1, mixed mode)
```
java.lang.IncompatibleClassChangeError: Method io.vertx.core.Future.succeededFuture()Lio/vertx/core/Future; must be InterfaceMethodref constant
        at net.iowntheinter.kvdn.server.impl.HTTPServer.init(HTTPServer.groovy:83)
        at vr.VRServer.lambda$start$2(VRServer.java:51)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
```

**Comment by vietj** [comment]
that's a groovy issue see multiple times with Java > 8 , have you tried with latest groovy 2.5 ?

**Comment by cinterloper** [comment]
Thanks for the info.

**Comment by Jezorko** [comment]
I got a similar error when using `Vertx.vertx()` (even with groovy 2.5).
The issue was that I was using a static import:

    import static io.vertx.core.Vertx.vertx
    // ...
    MongoClient.createShared(vertx(), configuration)

The issue was solved after changing it to:

    import io.vertx.core.Vertx
    // ...
    MongoClient.createShared(Vertx.vertx(), configuration)
