### ISSUE TITLE
problem with vertx-config-yaml

### ISSUE THREAD

**Issue by mnicik24** [eclipse/vert.x#2530]
### it throws Exception:

java.lang.IllegalArgumentException: unknown configuration format: yaml (supported formats are: [json, raw, properties]
	at io.vertx.config.impl.ConfigRetrieverImpl.<init>(ConfigRetrieverImpl.java:119)
	at io.vertx.config.ConfigRetriever.create(ConfigRetriever.java:49)
	at cn.cookie.common.config.Config.getConfig(Config.java:24)
	at cn.cookie.MainVerticle.start(MainVerticle.java:15)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:483)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cescoffier** [comment]
Can you check that in the fat jar you have the `META-INF/services/io.vertx.config.spi.ConfigProcessor` file contains the `io.vertx.config.yaml.YamlProcessor` line? 

If not configure your packaging to combine the different _contributions_ to this file.

**Comment by vietj** [comment]
can you move this issue in https://github.com/vert-x3/vertx-config ? thanks

**Comment by jdcapt** [comment]
There's strange thing though. first of all I have 2 files (???) `META-INF/services/io.vertx.config.spi.ConfigProcessor`. Both are identical and both contain one line - `io.vertx.config.yaml.YamlProcessor`.

And I have the same error as topic starter.

###HOWEVER

When I start it from IntelliJ IDEA - it magically works, it doesn't only if I start it from Terminal
