### ISSUE TITLE
get byte[] from JDBC for GZIP decompression

### ISSUE THREAD

**Issue by MeiyappanKannappa** [eclipse/vert.x#2571]
HI I have compressed data as byte[], stored in DB table column. I need to get the byte[] and decompress it. But there is no direct method to get data as byte[] in vert.x jdbc. I tried using getBinary(0) , but it throws me below exception

java.lang.IllegalArgumentException: Illegal base64 character 1f
	at java.util.Base64$Decoder.decode0(Base64.java:714)
	at java.util.Base64$Decoder.decode(Base64.java:526)
	at java.util.Base64$Decoder.decode(Base64.java:549)
	at io.vertx.core.json.JsonArray.getBinary(JsonArray.java:222)
	at com.example.test.WebVerticle.lambda$null$3(WebVerticle.java:138)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

Can anyone please help me out to decompress byte[] stored in DB.

**Comment by vietj** [comment]
can you open this issue on the vertx-jdbc-client repository instead ?
