### ISSUE TITLE
error on vertx sendMail, io.vertx.core.impl.ContextImpl - Unhandled exception java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by dhacker21** [eclipse/vert.x#2572]
hello i cannot catch null error on sending email
my code is like this :

```
fun sendMessage(data: JsonObject) : Observable<MailResult> {
         return observable<MailResult> {
            val message = MailMessage(data)
            mailClient.sendMail(message, it)
         }.doOnError {
             log.error("error on mailClient, move to resend"+it.message + " "+ it.getStackTraceAsString())
         }.onErrorReturn {
             null
         }.map {
             it
         }
    }
```
and try to use this, but still cannot catch the error on failed : 

```
mailClient.sendMail(message) {
             if (it.succeeded()) {} 
             else {
                  log.error("error on mailClient "+it.cause().printStackTrace())
             }
}
```
log error :

```
io.vertx.core.impl.ContextImpl - Unhandled exception
java.lang.NullPointerException: null
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:171)
    at io.vertx.ext.mail.impl.SMTPConnection.handleError(SMTPConnection.java:167)
    at io.vertx.ext.mail.impl.SMTPConnection.lambda$null$2(SMTPConnection.java:203)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
can you open this issue in the vertx-mail-client ? https://github.com/vert-x3/vertx-mail-client thanks
