### ISSUE TITLE
Vertx HTTP Thread block unknown warning issue

### ISSUE THREAD

**Issue by IdanFridman** [eclipse/vert.x#2598]
times to times we get this thread-block warning exception. any idea?

```
io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 1368 ms, time limit is 1000
io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.headers.VertxHttpHeaders.names(VertxHttpHeaders.java:337)
	at io.vertx.core.http.impl.headers.VertxHttpHeaders.size(VertxHttpHeaders.java:58)
	at io.vertx.core.http.impl.headers.VertxHttpHeaders.entries(VertxHttpHeaders.java:293)
	at io.vertx.core.http.impl.headers.VertxHttpHeaders.iterator(VertxHttpHeaders.java:322)
	at io.netty.handler.codec.http.HttpHeaders.set(HttpHeaders.java:1504)
	at io.netty.handler.codec.http.DefaultHttpHeaders.set(DefaultHttpHeaders.java:111)
	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:171)
	at io.netty.handler.codec.http.HttpContentEncoder.encode(HttpContentEncoder.java:51)
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88)
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116)
	at io.vertx.core.http.impl.HttpChunkContentCompressor.write(HttpChunkContentCompressor.java:38)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723)
	at io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:304)
	at io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:137)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.vertx.core.net.impl.ConnectionBase.write(ConnectionBase.java:107)
	at io.vertx.core.net.impl.ConnectionBase.lambda$queueForWrite$0(ConnectionBase.java:128)
	at io.vertx.core.net.impl.ConnectionBase$$Lambda$236/1662235749.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
	at io.vertx.core.impl.ContextImpl$$Lambda$23/1301528418.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by vietj** [comment]
it might happen if another task load your CPU and the thread is not able to make progress for 2 seconds (for instance a GC)

**Comment by vietj** [comment]
check with your GC
