### ISSUE TITLE
Websocket Request Failing to Upgrade

### ISSUE THREAD

**Issue by gtejasvi** [eclipse/vert.x#2612]
Websocket Request to upgrade fails with the below exception. The same was working on my local setup, but when deployed on a cluster started getting this error. 
The difference between the two websocket requests was that the first one was sending a response through as soon as it upgraded whereas the failing one was updating some shared data using an AsyncMap and sending a test message in the callBack. 
In effect the websocket closes down if the first message is not sent immediately after upgrading.

`Unhandled exception
java.lang.IllegalStateException: Can't upgrade this request
        at io.vertx.core.http.impl.Http1xServerConnection.upgrade(Http1xServerConnection.java:236)
        at io.vertx.core.http.impl.HttpServerRequestImpl.upgrade(HttpServerRequestImpl.java:317)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.upgrade(HttpServerRequestWrapper.java:223)
        at jdk.nashorn.internal.scripts.Script$Recompilation$2266$15438$\^eval\_#88\!17\^eval\_.L:1#HttpServerRequest#upgrade(vertx-js/http_server_request.js:498)
        at jdk.nashorn.internal.scripts.Script$Recompilation$2265$9296AA$\^eval\_#88\!17\^eval\_.L:1#L:223#upgradeWebSocket(server.js:248)
        at jdk.nashorn.internal.scripts.Script$Recompilation$2264$10109AA$\^eval\_#88\!17\^eval\_.L:1#L:223#L:276(server.js:280)
        at jdk.nashorn.internal.scripts.Script$Recompilation$2234$3355A$\^eval\_#88\!17\^eval\_.L:1#EventBus#send#L:79(vertx-js/event_bus.js:81)
        at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$convertHandler$1(EventBusImpl.java:349)
        at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:223)
        at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:200)
        at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:533)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:339)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by gtejasvi** [comment]
[Issue 2184](https://github.com/eclipse/vert.x/issues/2184) Found this to be similar but was closed with a different explanation. This as well could have been the reason for the issue too.

**Comment by vietj** [comment]
@gtejasvi can you show your code ?

**Comment by gtejasvi** [comment]
I think the primary issue was not with the response delay. Still trying to figure out how some of the requests actually send some response. But the primary reason for failure was because of the apache webserver. The new websocket url was not added to the RewriteRule, which did not allow it to be upgraded.
  `RewriteEngine On
   RewriteCond %{HTTP:Upgrade} =websocket [NC]
   RewriteRule ^/req/(socket1|socket2)/(.*) ws://<Internal Host>/req/$1/$2 [P,L]`
